### ISSUE TITLE
[Backend] Setting up the Review and Badge Schema

### ISSUE THREAD

**Issue by singhayushh** [ayan-biswas0412/gssoc2021-HotelOnTouch#100]
### Issue Reference
[View Issue Reference](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/issues/90#issuecomment-797267459)

### About this issue
Customers will have to option to review and rate the services and admins will have the feature the reward employees with badges for their work performance. Since these two models are relatively smaller and easier than User and Service, I have grouped them under a single issue. The work included: setting up two models - 1 for reviews and 1 for badges.

**Comment by ayan-biswas0412** [comment]
@singhayushh please update the issue body , like what is the work of this ```Setting up the Review and Badge Schema``` part only you can reference to my main issue on this but don't generalise the issues/PRs just make one issue -> one PR ,
you may raise as many as issues but provide proper brief description of work and link a single PR
