### ISSUE TITLE
[Backend] Basic User Endpoints

### ISSUE THREAD

**Issue by singhayushh** [ayan-biswas0412/gssoc2021-HotelOnTouch#101]
### Issue Reference
[View Issue Reference](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/issues/90#issuecomment-797267459)

### About this issue
The various operations or functionalities to be covered:
- CRUD users (as employee or customer)
- Hotel Room booking
- Admin routes to for making admin / removing admin (Users can only register as employees or customers. Only existing admins can add the admin role to others)

**Comment by ayan-biswas0412** [comment]
keep one single task list and link multiple issue in the 'Task List' only don't mention all them at all places
