### ISSUE TITLE
[Backend] Basic Service Endpoints

### ISSUE THREAD

**Issue by singhayushh** [ayan-biswas0412/gssoc2021-HotelOnTouch#102]
### Issue Reference
[View Issue Reference](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/issues/90#issuecomment-797267459)

### About this issue
The various operations or functionalities to be covered:
- CRUD Services (admins only)
- Request a service (customer only)
- Assign and track service (admins only)

**Comment by udaymittal7** [comment]
@ayan-biswas0412 Can i take this task as a participant of GSSOC'21?

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 Can i take this task as a participant of GSSOC'21?

please clarify from @singhayushh , 
@singhayushh can you guide him regarding the work ?

**Comment by singhayushh** [comment]
Yes surely,
@udaymittal7, before you start the work you need to have a clear idea of the project backend - what all features are in target. To work on this issue, the service model needs to be created and approved before working with the endpoints. There is a separate issue raised for the service and you have to work on that before taking up the current issue. Or just wait till someone works with the service model and gets the schema approved.

**Comment by ayan-biswas0412** [comment]
@singhayushh I will merge your PR with first priority , please resolve the thing I have commented and ask for a review I will merge it

**Comment by udaymittal7** [comment]
@singhayushh Yeah, I have read the reference issue. Can we have a meet or proper discussion about how the whole backend will be build so we all can divide the tasks and know what we have to do. Just a suggestion.

**Comment by singhayushh** [comment]
@udaymittal7 
We can talk over discord if you'd want.

**Comment by ayan-biswas0412** [comment]
> @udaymittal7
> We can talk over discord if you'd want.

ping me over then then we can decide a time

**Comment by udaymittal7** [comment]
@ayan-biswas0412 @singhayushh Yeah we can discuss over the project channel so other participants can discuss too.

**Comment by singhayushh** [comment]
@udaymittal7 My PR for service schema has been merged yesterday finally. Now you may proceed with the end points and modifications. Do not forget to checkout and reply in issues 144, 145, 146 and 147.
