### ISSUE TITLE
[Backend] Review and Badge Endpoints

### ISSUE THREAD

**Issue by singhayushh** [ayan-biswas0412/gssoc2021-HotelOnTouch#103]
### Issue Reference
[View Issue Reference](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/issues/90#issuecomment-797267459)

### About this issue
The various operations or functionalities to be covered:
- CRUD Badges (admins only)
- Assign badges (admins only)
- Review service (customers only)

**Comment by abhinav5481** [comment]
Hi
I would like to work on this issue as part of GSSOC'21. Could you please assign it to me ?

**Comment by ayan-biswas0412** [comment]
> Hi
> I would like to work on this issue as part of GSSOC'21. Could you please assign it to me ?

kindly consult with @singhayushh

**Comment by singhayushh** [comment]
@abhinav5481, sure you can work on this. Checkout issue 100 and work on that before starting with this issue.
All the best!
