### ISSUE TITLE
Add Styling to Jumbotron/Homepage Heading div

### ISSUE THREAD

**Issue by ankitaugale23** [ayan-biswas0412/gssoc2021-HotelOnTouch#104]
Adding styling and some effects to jumbotron at the top of the homepage. 
@ayan-biswas0412 please add respective tags with GSSoC tag also so I can start working on the issue.

**Comment by ankitaugale23** [comment]
I will make a PR tomorrow till 9 pm.

**Comment by ankitaugale23** [comment]
I am done with the work. But just wanted to confirm once that I have added an extra react library to implement some functionality. 
So should I go ahead and make a PR. (ASking this because you haven't explicitly mentioned it and I did that for one project and it was not allowed.) Kindly tell me what should I do?

**Comment by ayan-biswas0412** [comment]
> I am done with the work. But just wanted to confirm once that I have added an extra react library to implement some functionality.
> So should I go ahead and make a PR. (ASking this because you haven't explicitly mentioned it and I did that for one project and it was not allowed.) Kindly tell me what should I do?

sure no problem just mention it in PR message

**Comment by ankitaugale23** [comment]
sure thanks. Making a PR now.
