### ISSUE TITLE
Improve the Contribution section and fix the footer

### ISSUE THREAD

**Issue by cryptofox17** [ayan-biswas0412/gssoc2021-HotelOnTouch#105]
**Describe the bug**
This isn't a bug, but the footer doesn't occupy 100% of the width on mobile devices. So I want to make it responsive. Also, want to enhance the contribution section as right now it occupies a lot of space since there are only 2 cards per row.

**To Reproduce**
-

**Expected behavior**
Footer to be responsive

**Screenshots**
-

**Device Information [optional]:**

-

**Additional context**
-

**Are you working on this issue? (Yes/No)**
Yes

Please assign this issue to me as a part of GSSOC21

**Comment by ayan-biswas0412** [comment]
> **Describe the bug**
> This isn't a bug, but the footer doesn't occupy 100% of the width on mobile devices. So I want to make it responsive. Also, want to enhance the contribution section as right now it occupies a lot of space since there are only 2 cards per row.
> 
> ## **To Reproduce**
> Steps to reproduce the behavior:
> **Expected behavior**
> Footer to be responsive
> 
> ## **Screenshots**
> **Device Information [optional]:**
> 
> 
> ## **Additional context**
> **Are you working on this issue? (Yes/No)**
> Yes
> 
> Please assign this issue to me as a part of GSSOC21

sure

**Comment by cryptofox17** [comment]
Thank you for assigning me this issue @ayan-biswas0412

**Comment by aniketsingh98571** [comment]
@cryptofox17 Can you provide a screenshot of which device the footer is not taking the full 100% width because I only made the footer, so after that, I checked it too and also just checked now on all devices it is working fine.

**Comment by cryptofox17** [comment]
@aniketsingh98571 I just checked it on my phone and it didn't take 100% of the width. But on chrome dev tools it works fine except for galaxy fold device. 
I am attaching the screenshot showing how it looks on my phone : 
![Screenshot_20210313-224523481](https://user-images.githubusercontent.com/64403591/111038283-1f289180-844e-11eb-8f82-19f925f3960b.jpg)

**Comment by ayan-biswas0412** [comment]
> @aniketsingh98571 I just checked it on my phone and it didn't take 100% of the width. But on chrome dev tools it works fine except for galaxy fold device.
> I am attaching the screenshot showing how it looks on my phone :
> ![Screenshot_20210313-224523481](https://user-images.githubusercontent.com/64403591/111038283-1f289180-844e-11eb-8f82-19f925f3960b.jpg)

you may raise a bug on this
