### ISSUE TITLE
Tech Stack Update ( LOGO add ) 

### ISSUE THREAD

**Issue by rohank2502** [ayan-biswas0412/gssoc2021-HotelOnTouch#107]
I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!

**Comment by ayan-biswas0412** [comment]
@rohank2502 can you explain more what you want to do in this ?

**Comment by rohank2502** [comment]
> 
> 
> @rohank2502 can you explain more what you want to do in this ?

I will like to add the logo of each tech stack used as img

**Comment by ayan-biswas0412** [comment]
> > @rohank2502 can you explain more what you want to do in this ?
> 
> I will like to add the logo of each tech stack used as img

ohh sure

**Comment by rohank2502** [comment]
Thanks !!

**Comment by rohank2502** [comment]
Please Assign this issue to me so I can start work on this !

**Comment by ayan-biswas0412** [comment]
> Please Assign this issue to me so I can start work on this !

sure

**Comment by silentWatcher3** [comment]
> Please Assign this issue to me so I can start work on this !

@rohank2502 start "work" on this you mean 👍
