### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohank2502** [ayan-biswas0412/gssoc2021-HotelOnTouch#108]
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by ayan-biswas0412** [comment]
sure go ahead @rohank2502

**Comment by rohank2502** [comment]
> 
> 
> sure go ahead @rohank2502

Thanks !!
