### ISSUE TITLE
Add GSSoc 2021 logo in Readme

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#11]
**Is your feature request related to a problem? Please describe.**
Add a logo of GSSoc 2021 in Readme file below the line we are now part of GSSoc 2021

**Describe the solution you'd like**
Follow proper markdown rules to add the logo and take the logo from GSSoc official website.
keep the logo as```docs/gsssoc2021_logo.png```

**Comment by anushkasinghal11** [comment]
Hey!
Can I take this up?

**Comment by ayan-biswas0412** [comment]
> Hey!
> Can I take this up?

Go ahead

**Comment by ayan-biswas0412** [comment]
@anushkasinghal11 I would like to confirm you that towards GSsoc 2021 it will be counted as a valid contribution if your PR is placed on or after March 1

**Comment by ayan-biswas0412** [comment]
@anushkasinghal11 I am unassigning you for now and I will assign you again on 1 March

**Comment by rajeshpanjiyar** [comment]
I would like to work on this so i am requesting you to assign me this task.

**Comment by ayan-biswas0412** [comment]
> I would like to work on this so i am requesting you to assign me this task.

you are assigned in another one please complete that first

**Comment by rajeshpanjiyar** [comment]
Please assign me on this, I want to work on this too.

**Comment by ayan-biswas0412** [comment]
@rajeshpanjiyar keep patience 🥰 you will be assigned only after completion of previous job

**Comment by shreyanshi16** [comment]
Hey! I am a part of GSSoc program and I would like to solve this issue. Can you please assign this issue to me?

**Comment by ayan-biswas0412** [comment]
Hi @shreyanshi16 thank you for your interest but this issue was previously assigned to @anushkasinghal11 but you can take this and make a PR but if she does a PR first then we will give preference to her PR you may look for the other issues in this repo or you can take this issue also
