### ISSUE TITLE
Adding various security features

### ISSUE THREAD

**Issue by udaymittal7** [ayan-biswas0412/gssoc2021-HotelOnTouch#115]
Setting various HTTP headers using helmet
Data sanitization against no SQL injection and XSS
Rate limiter so the server won't get overload

If you find it relevant, please assign me.
I am a participant of GSSOC'21 so please add the relevant GSSOC tags too.

**Comment by ayan-biswas0412** [comment]
> Setting various HTTP headers using helmet
> Data sanitization against no SQL injection and XSS
> Rate limiter so the server won't get overload
> 
> If you find it relevant, please assign me.
> I am a participant of GSSOC'21 so please add the relevant GSSOC tags too.

yah sure you can work on this
