### ISSUE TITLE
[FRONTEND] [GSSOC' 21] Adding dark mode to the website

### ISSUE THREAD

**Issue by Aditya201551** [ayan-biswas0412/gssoc2021-HotelOnTouch#119]
Adding a toggle button on the navbar so the user can toggle to light and dark mode anywhere anytime

@ayan-biswas0412  I Would like to contribute to this feature so it would be great if you assign me this task!

ThankYou(GSSOC '21 participant)

**Comment by ayan-biswas0412** [comment]
Duplicate #94 issue please see that one and you can work on that issue I am closing this

**Comment by Aditya201551** [comment]
okay
