### ISSUE TITLE
Setup an express app and create folder backend

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#12]
**Is your feature request related to a problem? Please describe.**
setup an initial express app using the standard method and just setup the app and run , add proper environment variable for PORTS and other things the expressapp should be under ```backend``` folder under the main repository. 

name of the npm package should be : backendhotelontouch

**Comment by chaimat** [comment]
Hey! Can I take this up?

**Comment by ayan-biswas0412** [comment]
> Hey! Can I take this up?

Go ahead

**Comment by ayan-biswas0412** [comment]
@chaimat are you working on this ?

**Comment by ashirbad29** [comment]
if the issue is still not resolved,  i want to work on this.

**Comment by ayan-biswas0412** [comment]
> if the issue is still not resolved, i want to work on this.

let's wait for @chaimat if he doesn't reply I will assign it to you

**Comment by chaimat** [comment]
I was waiting for 1st March as that's when we were asked to send in the PRs for GSSOC 2021 as @ayan-biswas0412 also mentioned in one of the other issues. I have completed the task, was just waiting for the event to begin. I can send in the pull request now as well.

**Comment by ayan-biswas0412** [comment]
> I was waiting for 1st March as that's when we were asked to send in the PRs for GSSOC 2021 as @ayan-biswas0412 also mentioned in one of the other issues. I have completed the task, was just waiting for the event to begin. I can send in the pull request now as well.

sure

**Comment by chaimat** [comment]
So should I send in the pull request now?

**Comment by chaimat** [comment]
So should I send in the pull request now?

**Comment by ayan-biswas0412** [comment]
> So should I send in the pull request now?

if you have done, you can send PR for review
