### ISSUE TITLE
Docker Configuration needed for local development

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#122]
**Is your feature request related to a problem? Please describe.**
Looking for suggestions that how a docker composer can be done such that user has not to take headache to setup project locally

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by ayan-biswas0412** [comment]
> Can I work on this issue under GSSoC'21? Kindly assign it to me.

you are already assigned to another one I think

**Comment by jain-rishabh-21** [comment]
Hey can you assign it to me!
Discord: krackerzzz#4371

**Comment by ayan-biswas0412** [comment]
> Hey can you assign it to me!
> Discord: krackerzzz#4371

have you worked in docker before ?

**Comment by jain-rishabh-21** [comment]
Yes I have worked on docker before, sorry to reply late, please assign me the issue

**Comment by subhangi2731** [comment]
please assign me this

**Comment by jain-rishabh-21** [comment]
Currently working will raise a PR

**Comment by subhangi2731** [comment]
@ayan-biswas0412 please assign me I can work on this

**Comment by Jassi10000-zz** [comment]
@ayan-biswas0412 Is that issue related to dockerizing the application 
If yes , then I want to definitely try my hands out on this 
You can assign me after @subhangi2731 does with her part

**Comment by subhangi2731** [comment]
@Jassi10000 I have already started working on this and will send a pr and I think the issue will be closed after my pr gets merged

**Comment by Jassi10000-zz** [comment]
@subhangi2731 I know , no issues with that 
That's why I wrote  that he can assign me after you 
which means in case the result is not as expected  , I can try on that

But if you are good with that , then no issues 
All the best

**Comment by subhangi2731** [comment]
@ayan-biswas0412 should the backend be dockerised so that nodejs and all dependencies inside backend folder are installed ?
please tell me soon as I will be creating a pr now

**Comment by subhangi2731** [comment]
@bhavita2404 can u please reply here i guess u are the mentor of this project
