### ISSUE TITLE
Create a app launching page in hotelontouch 

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#123]
**Is your feature request related to a problem? Please describe.**
make a page /applaunch inside hotelontouch
the page should describe app of hotelontouch you may use cool svgs and make it creative and all components should reside under /components

**Comment by abhishek7997** [comment]
Please assign me the issue. @ayan-biswas0412

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by ayan-biswas0412** [comment]
preference will be given to most creative designs

**Comment by abhishek7997** [comment]
@ayan-biswas0412 Should I add a redirect to '/applaunch' as well? Or just creating the files is needed?

**Comment by ayan-biswas0412** [comment]
reopen
