### ISSUE TITLE
backend deployment suggestions

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#125]
**Is your feature request related to a problem? Please describe.**
how to deploy properly the backend some ideas needed

**Comment by ayan-biswas0412** [comment]
@singhayushh can you put your thoughts

**Comment by singhayushh** [comment]
If this application is just a working prototype of the idea rather than a full fledged application, I'd recommend heroku as it is better suited for backend hosting.

**Comment by ayan-biswas0412** [comment]
> If this application is just a working prototype of the idea rather than a full fledged application, I'd recommend heroku as it is better suited for backend hosting.

yah I also feel same can you provide me detailed steps to deploy to Heroku ?

**Comment by singhayushh** [comment]
There are two ways by which you can deploy the app on heroku. 
One is using just the online interface which is really very simple and easy to use. You just need to sign up on the [heroku platform](https://dashboard.heroku.com/apps), create a new app followed by linking the repository and simply opting for automatic deployment or manual deployment. 

The other is using git cli, if you like to work with the keyboard more than the mouse. Here's the official documentation with all necessary steps - [View Docs](https://devcenter.heroku.com/articles/git)

Note: To deploy on heroku, the repository needs to have a `Procfile` to hold the entry point to the web server (for this case, it'll be `web: npm start`)

**Comment by aniketsingh98571** [comment]
@singhayushh @ayan-biswas0412 I think we are using nodejs in this project, so will it be required to add serverless functions to it...because I have one of my projects made using nodejs but as soon as I deployed it on netlify it gave an error regarding you need serverless functions for it........

**Comment by singhayushh** [comment]
I have deployed general nodejs applications on heroku before without the errors you mentioned of. But if we are able to add serverless functions, it'll be really great as there are a lot of advantages of serverless apps.

**Comment by aniketsingh98571** [comment]
> I have deployed general nodejs applications on heroku before without the errors you mentioned of. But if we are able to add serverless functions, it'll be really great as there are a lot of advantages of serverless apps.

Can you guide me how to deploy [this](https://github.com/aniketsingh98571/HeaLearn) on netlify or heroku

**Comment by singhayushh** [comment]
> Can you guide me how to deploy [this](https://github.com/aniketsingh98571/HeaLearn) on netlify or heroku

You need to have your app.js in the root directory. Workaround for sub directories -> [View Solution](https://github.com/heroku/heroku-buildpack-nodejs/issues/385)

**Comment by ayan-biswas0412** [comment]
@singhayushh can you guide me like our backend folder is only needed to be deployed in the Heroku (not the entire repo so how to do that)

**Comment by singhayushh** [comment]
Okay. I'll need a week's time though. Have exams going on. Please excuse me for a week 😅
