### ISSUE TITLE
make bottomNavigator is customerfrontend

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#13]
**Is your feature request related to a problem? Please describe.**
you have to make an bootmnavigator consisting of four options 
1. Home
2. Options
3. About
4. Profile

choose appropriate material icons and also in each page show one like "This is page_name page"

**Comment by khushi935** [comment]
I like to work on this. please assign it to me.😊

**Comment by khushi935** [comment]
![Screenshot (84)](https://user-images.githubusercontent.com/62712155/108503233-09ee9600-72da-11eb-9623-d1350d5e98fc.png)
It's showing like this. What should I do now?

**Comment by ayan-biswas0412** [comment]
> ![Screenshot (84)](https://user-images.githubusercontent.com/62712155/108503233-09ee9600-72da-11eb-9623-d1350d5e98fc.png)
> It's showing like this. What should I do now?

Thank you for running the project successfully locally but you have to connect android device/ emulator to run the app please refer the video https://www.youtube.com/watch?v=uqGEc5dywzo&t=118s

**Comment by khushi935** [comment]
same warn and information is showing.

**Comment by ayan-biswas0412** [comment]
> same warn and information is showing.

Have you followed all the steps in the video ? And check if your android studio and android sdk is installed properly and set the local.properties file (Google it how to setup this) and then perform the adb reverse as said In video i think this  will sort your issue

**Comment by khushi935** [comment]
> > same warn and information is showing.
> 
> Have you followed all the steps in the video ? And check if your android studio and android sdk is installed properly and set the local.properties file (Google it how to setup this) and then perform the adb reverse as said In video i think this will sort your issue

I have to download android studio? I just download the platform-tool as shown in vedio.

**Comment by ayan-biswas0412** [comment]
@khushi935 I am unassigning you for now , if you have done the local setup please inform me then I will assign you again

**Comment by khushi935** [comment]
yeah ok

**Comment by ayan-biswas0412** [comment]
@khushi935 do you want to work in this ?

**Comment by subhangi2731** [comment]
can you please assign this to me?

**Comment by ayan-biswas0412** [comment]
@subhangi2731 work for a single issue please

**Comment by nehathakur27** [comment]
I would like to work on this issue.

**Comment by nehathakur27** [comment]
![Screenshot_20210311-201627](https://user-images.githubusercontent.com/36047037/110805409-0e89e700-82a7-11eb-96e3-eee2e7420363.jpg)
@ayan-biswas0412  Is this okay?

**Comment by ayan-biswas0412** [comment]
> ![Screenshot_20210311-201627](https://user-images.githubusercontent.com/36047037/110805409-0e89e700-82a7-11eb-96e3-eee2e7420363.jpg)
> @ayan-biswas0412 Is this okay?

make a PR and attach all screenshots in the PR message
