### ISSUE TITLE
[Backend] Middleware for user authentication needed

### ISSUE THREAD

**Issue by singhayushh** [ayan-biswas0412/gssoc2021-HotelOnTouch#131]
**Is your feature request related to a problem? Please describe.**
A middleware for user authentication is needed to limit access to certain routes.

**Describe the solution you'd like**
The middleware should access the jwt token from the Authentication Header, decode it to fetch the email and _id of the user. It should then search for the user either in the Staff collection or the Customer collection. If found, the user's email, _id and user_id should be added to the request body.

**Are you working on this? (Yes/No)**
Yes, if approved. A PR can be expected within 2 days.

**Comment by ayan-biswas0412** [comment]
issue labelled and assigned to @singhayushh
