### ISSUE TITLE
Adding register/signin page

### ISSUE THREAD

**Issue by ooreally** [ayan-biswas0412/gssoc2021-HotelOnTouch#132]
@ayan-biswas0412 I would like to add a register (#action/3.1) / SignIn   (#action/3.2 ) page whenever a user clicks on register or signIn.

**Comment by Vi1234sh12** [comment]
Hii @JanviMahajan14,  can  I work on this issue?

**Comment by ayan-biswas0412** [comment]
go ahead @ooreally

**Comment by ShambhaviSharma0110** [comment]
hey! I would like to work on this please allow me...
-gssoc '21 participant

**Comment by ayan-biswas0412** [comment]
> hey! I would like to work on this please allow me...
> -gssoc '21 participant

you are already assigned to another issue

**Comment by ooreally** [comment]
@ayan-biswas0412 thanks for assigning.

**Comment by sandra9711** [comment]
@ayan-biswas0412 
I'm a GSSOC'21 participant. can I work on this issue?

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412
> I'm a GSSOC'21 participant. can I work on this issue?

go ahead

**Comment by Ankita297** [comment]
@ayan-biswas0412  Can i work on this ?

**Comment by Ankita297** [comment]
@ayan-biswas0412 ?

**Comment by Ankita297** [comment]
Can i work on this @ayan-biswas0412 ?

**Comment by ooreally** [comment]
PR#163 made for this issue. Please review it @ayan-biswas0412
