### ISSUE TITLE
Restaurant dashboard making 

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#134]
**Is your feature request related to a problem? Please describe.**
A restaurant side dashboard need to be made all the works should be done in the ```hotel-restraunt-fronted``` this is an advanced level issue requires multiple contributions and also looking for new ideas , this issue will accept multiple PRs from multiple persons

**Comment by ShambhaviSharma0110** [comment]
hey! I would like to work on this please allow me...
-gssoc '21 participant

**Comment by ayan-biswas0412** [comment]
> hey! I would like to work on this please allow me...
> -gssoc '21 participant

sure go ahead

**Comment by Ankita297** [comment]
@ayan-biswas0412  can i work on this ?
Basically we have to add like services that we provide or anything else ?
