### ISSUE TITLE
Navbar Improvement

### ISSUE THREAD

**Issue by shawavisek35** [ayan-biswas0412/gssoc2021-HotelOnTouch#141]
**Is your feature request related to a problem? Please describe.**
Currently, the Navbar of the website is looking kinda very simple, and to attract visitors to the website I think we need a good navbar.

**Describe the solution you'd like**
I would like to change the design of the Navbar.

**Describe alternatives you've considered**
I would make fonts a little fancier and would use a better colour pallet for the Navbar and would change it's design as well.

**Additional context**
I don't have any screenshots to provide but I have worked on this type of thing and would promise to give you the best result.

**Are you working on this? (Yes/No)**
Yes, I would like to work on this issue.

**Comment by ayan-biswas0412** [comment]
> **Is your feature request related to a problem? Please describe.**
> Currently, the Navbar of the website is looking kinda very simple, and to attract visitors to the website I think we need a good navbar.
> 
> **Describe the solution you'd like**
> I would like to change the design of the Navbar.
> 
> **Describe alternatives you've considered**
> I would make fonts a little fancier and would use a better colour pallet for the Navbar and would change it's design as well.
> 
> **Additional context**
> I don't have any screenshots to provide but I have worked on this type of thing and would promise to give you the best result.
> 
> **Are you working on this? (Yes/No)**
> Yes, I would like to work on this issue.

sure
