### ISSUE TITLE
Backend api needed for restaurant service management

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#144]
**Is your feature request related to a problem? Please describe.**
check the ```backend``` folder to understand the structure and this api is for managing of hotel services please feel free to discuss about data models like how to manage various hotel service and what are the end points needed please comment on this issue first and make your choice and make another issue based on what you want to do about this and link the issue here and I will label them based on the difficulty

**Comment by Athira2199** [comment]
Hi @ayan-biswas0412 I think it would be helpful, if you make a list of requirements this endpoint has to suffice. By doing that it will be easier to come to a conclusion as what all would be the endpoints that we have to design. Based on that we could prepare a swagger documentation. Then it would be easier to go on with the development process. We will be using NodeJS for providing different APIs to the end applications right. Or are we planning server rendered application for any of the modules like admin etc.

**Comment by ayan-biswas0412** [comment]
> Hi @ayan-biswas0412 I think it would be helpful, if you make a list of requirements this endpoint has to suffice. By doing that it will be easier to come to a conclusion as what all would be the endpoints that we have to design. Based on that we could prepare a swagger documentation. Then it would be easier to go on with the development process. We will be using NodeJS for providing different APIs to the end applications right. Or are we planning server rendered application for any of the modules like admin etc.

you can check the backend folder already swagger is integrated and documentation part is ok basically for restraunt serve management here is the workflow what I need in the main application

user logged in to account -> can see various restraunts of his/her hotel -> choose restaurant -> add food to cart -> order them -> pay by cash/online -> invoice generation

**Comment by Sukriti-sood** [comment]
@ayan-biswas0412 I want to work on this

**Comment by subhangi2731** [comment]
please assign me this

**Comment by subhangi2731** [comment]
@ayan-biswas0412 I want to work on this and will send a pr in 2 days please assign me this

**Comment by subhangi2731** [comment]
@ayan-biswas0412 ?

**Comment by subhangi2731** [comment]
@ayan-biswas0412 please assign me on this

**Comment by subhangi2731** [comment]
@ayan-biswas0412 I request u please assign me I have commented so many times
