### ISSUE TITLE
Backend api needed for laundry service management 

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#145]
**Is your feature request related to a problem? Please describe.**
check the ```backend``` folder to understand the structure and this api is for managing of hotel services please feel free to discuss about data models like how to manage various hotel service and what are the end points needed please comment on this issue first and make your choice and make another issue based on what you want to do about this and link the issue here and I will label them based on the difficulty

**Comment by Sukriti-sood** [comment]
This is can have a laundary order model that will include information about  type of laundry service,  number of clothes, special instructions, and location.
