### ISSUE TITLE
Some new ideas needed to enhance the fronted of various web components

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#148]
**Is your feature request related to a problem? Please describe.**
There are several web apps in this project so looking for ideas for enhancing them looking for ideas . please feel free to open issues.Check various folders for react apps.

### Note
Minor colour change improvement is not acceptable
Minor font improvement is strongly discouraged

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by ayan-biswas0412** [comment]
> Can I work on this issue under GSSoC'21? Kindly assign it to me.

I think you have not read the issue

**Comment by GurshehzadSingh** [comment]
adding a button on bottom right so that when user hits it, the onclick function of the button takes the user to the top of the website

**Comment by ayan-biswas0412** [comment]
> adding a button on bottom right so that when user hits it, the onclick function of the button takes the user to the top of the website

yah you can make one issue and start working

**Comment by GurshehzadSingh** [comment]
Alright

**Comment by CMELAKKIA** [comment]
i can add new themes to the website

**Comment by CMELAKKIA** [comment]
@ayan-biswas0412  I can also enhance the style of all the buttons

**Comment by rakup444** [comment]
@ayan-biswas0412 
I want to move the search bar (in the navbar) to the center.
And make the register, login & contact us buttons on the right side as a legend and remove the SignUp/SignIn menu.

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412
> I want to move the search bar (in the navbar) to the center.
> And make the register, login & contact us buttons on the right side as a legend and remove the SignUp/SignIn menu.

make an proper issue and start working

**Comment by bswethareddy** [comment]
@ayan-biswas0412 I want to contribute to this project and add Sign In and Sign Up pages to the project. I can ensure that I will add them in same format and same theme as contact page.

**Comment by subhangi2731** [comment]
please assign me this. I will make a pr by tomorrow
