### ISSUE TITLE
UI Design for Homepage

### ISSUE THREAD

**Issue by shreyanshi16** [ayan-biswas0412/gssoc2021-HotelOnTouch#149]
**Is your feature request related to a problem? Please describe.**
Design the UI of the whole homepage so that all the components can be designed according to a fixed layout.

**Are you working on this? (Yes/No)**
Yes, I want to work on this issue.

**Comment by ayan-biswas0412** [comment]
@shreyanshi16 in which tool you want to design it I would suggest you in figma

**Comment by shreyanshi16** [comment]
Ya, I will design it in Figma. I want to ask which color scheme and font you want?

**Comment by ayan-biswas0412** [comment]
> Ya, I will design it in Figma. I want to ask which color scheme and font you want?

be creative as much as you can and follow the colour scheme of the main website

**Comment by shreyanshi16** [comment]
https://user-images.githubusercontent.com/53462278/112747416-f0c0bf80-8fd2-11eb-868a-1e52c6fdb62b.mp4


Here is the UI design of the Homepage. Please have a look!

**Comment by aniketsingh98571** [comment]
>  WhatsApp.Video.2021-03-28.at.2.29.55.PM.mp4 
> Here is the UI design of the Homepage. Please have a look!

@shreyanshi16 Its pretty good and clean....great work....just one suggestion, in the Lead Developer section of @ayan-biswas0412 
Please add all the links to the card only...
For your reference 0:30 secs in the video.... rest @ayan-biswas0412  will know pretty more about it....

**Comment by ayan-biswas0412** [comment]
@aniketsingh98571 what you have suggested is very good 
but @shreyanshi16 till now our primary need is to design the actual platform and your design is very good no doubt but you can try to design one single end like maybe the hotel admin app or the guest app.

**Comment by shreyanshi16** [comment]
@aniketsingh98571 Thank you and I will make the suggested changes.
@ayan-biswas0412 I thought you want to enhance the frontend of the existing website but no problem I will try to design one single end.

**Comment by ayan-biswas0412** [comment]
> @aniketsingh98571 Thank you and I will make the suggested changes.
> @ayan-biswas0412 I thought you want to enhance the frontend of the existing website but no problem I will try to design one single end.

yeah sure
