### ISSUE TITLE
Setup React Router for  hotel-admin-frontend

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#15]
**Describe the solution you'd like**
Add routes for different pages make page_one.js and page_two.js and define their corresponding routes under ```src/App.js``` and also integrate [React Bootstrap](https://react-bootstrap.github.io)

all pages should be under ```src/pages```

show one bootstrap <Card> in both of the pages containing text like ```This is the page one```

**Describe alternatives you've considered**

**Additional context**
NA

**Comment by Doringl** [comment]
I can also help this issue.

**Comment by ayan-biswas0412** [comment]
> I can also help this issue.

Yeah go ahead

**Comment by ayan-biswas0412** [comment]
closed via #27
