### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by sonal251001** [ayan-biswas0412/gssoc2021-HotelOnTouch#152]
**Is your feature request related to a problem? Please describe.**
In the README.md we could add a list of open-source oraganisations that this project has been a part of.
**Describe the solution you'd like**

**Describe alternatives you've considered**
Hello, I am a GSSoC paticipant and I would like to work on this. Please see if it is applicable.
**Additional context**

**Are you working on this? (Yes/No)**
Yes will work if I'm assigned with relavent details

**Comment by ayan-biswas0412** [comment]
@sonal251001 i have already said that this type of small changes will not be entertained
