### ISSUE TITLE
Adding Order Api and Menu

### ISSUE THREAD

**Issue by Sukriti-sood** [ayan-biswas0412/gssoc2021-HotelOnTouch#153]
Relate to issue  #147
For Food Odering System , I was thinking of Having of having Order and Menu Order
Order Model will contain:-
- Customer (Object Id)
- Dishes (Array of Object Id of Menu Items)

Menu  Model will contain:-
- DIsh Name
- Dish Price

@ayan-biswas0412  Have a look at issue and I want to work on this

I want to make this functionality using Mongodb and express framework(nodejs )

**Comment by ayan-biswas0412** [comment]
@Sukriti-sood go ahead
