### ISSUE TITLE
contact path is reloading

### ISSUE THREAD

**Issue by hsnice16** [ayan-biswas0412/gssoc2021-HotelOnTouch#156]
**Describe the bug**
When we are clicking on the contact us option from the homepage. The page is getting reload. But as we are using react Js for the frontend. We can prevent it from reloading.

**Expected behavior**
When we click on the contact us option, only the path should change. And this should happen without reloading the page.

**Are you working on this issue? (Yes/No)**
Yes, I would like to work on this issue.

**Comment by ayan-biswas0412** [comment]
Go ahead @hsnice16 and nice bug finding

**Comment by hsnice16** [comment]
Can you please merge my PR for contact path is reloading issue. I just got
an email from stale bot that the issue will get closed.

**Comment by hsnice16** [comment]
why the wontfix label?
