### ISSUE TITLE
Configure eslint and prettier for the UI application 

### ISSUE THREAD

**Issue by PuneetPunamiya** [ayan-biswas0412/gssoc2021-HotelOnTouch#157]
Configure eslint and prettier for the UI application 

- The UI application should have a lint and prettier configuration which will
keep the code in one format (for e.g. proper spacing, etc) and will make 
the code look preetier as well

 - Configuring `eslint` and `preetier`  and executing the commands like 
 `npm run lint` and `npx prettier --write .`  will give the warnings/errors
  which the developers can fix before the code is submitted

**Comment by PuneetPunamiya** [comment]
Hey @ayan-biswas0412 
I'm the participant of GSSOC'21 could you please assign me this issue

**Comment by ayan-biswas0412** [comment]
> Hey @ayan-biswas0412
> I'm the participant of GSSOC'21 could you please assign me this issue

if is there any GitHub action there please search on that because we don't want to run manual test
