### ISSUE TITLE
Correcting the English grammar, spelling, punctuation on the home page

### ISSUE THREAD

**Issue by sharvariiii** [ayan-biswas0412/gssoc2021-HotelOnTouch#158]
Hello Mentors , I wish to correct some of the English grammar, spelling, punctuation on the home page so that it will be more appealing .Looking forward to working on this issue as a GSSOC 21 participant. Thank you:)

**Comment by ayan-biswas0412** [comment]
> Hello Mentors , I wish to correct some of the English grammar, spelling, punctuation on the home page so that it will be more appealing .Looking forward to working on this issue as a GSSOC 21 participant. Thank you:)

can you be more specific what are wrong , and I will me more than happy if you modify contents of various pages

**Comment by sharvariiii** [comment]
> > Hello Mentors , I wish to correct some of the English grammar, spelling, punctuation on the home page so that it will be more appealing .Looking forward to working on this issue as a GSSOC 21 participant. Thank you:)
> 
> can you be more specific what are wrong , and I will me more than happy if you modify contents of various pages

Corrections are shown in blue rectangle. Can I go ahead with this?

![pic1](https://user-images.githubusercontent.com/78595265/112728304-911fd100-8f4c-11eb-95c2-c70da4d55869.png)

![pic2](https://user-images.githubusercontent.com/78595265/112728300-8ebd7700-8f4c-11eb-882d-4e59d9d611c3.png)

![pic3](https://user-images.githubusercontent.com/78595265/112728303-90873a80-8f4c-11eb-880b-b6eb59f34cdf.png)

**Comment by ayan-biswas0412** [comment]
> > > Hello Mentors , I wish to correct some of the English grammar, spelling, punctuation on the home page so that it will be more appealing .Looking forward to working on this issue as a GSSOC 21 participant. Thank you:)
> > 
> > 
> > can you be more specific what are wrong , and I will me more than happy if you modify contents of various pages
> 
> Corrections required are shown in blue rectangle. Can I go ahead with this?
> 
> ![pic1](https://user-images.githubusercontent.com/78595265/112728304-911fd100-8f4c-11eb-95c2-c70da4d55869.png)
> 
> ![pic2](https://user-images.githubusercontent.com/78595265/112728300-8ebd7700-8f4c-11eb-882d-4e59d9d611c3.png)
> 
> ![pic3](https://user-images.githubusercontent.com/78595265/112728303-90873a80-8f4c-11eb-880b-b6eb59f34cdf.png)

go ahead
