### ISSUE TITLE
setup React router for hotel-restraunt-frontend

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#16]
**Describe the solution you'd like**
Add routes for different pages make page_one.js and page_two.js and define their corresponding routes under ```src/App.js``` and also integrate [React Bootstrap](https://react-bootstrap.github.io)

all pages should be under ```src/pages```

show one bootstrap <Card> in both of the pages containing text like ```This is the page one```

**Describe alternatives you've considered**

**Additional context**
NA

**Comment by Doringl** [comment]
I can help you if you want ? :)

**Comment by ayan-biswas0412** [comment]
> I can help you if you want ? :)

You are already assigned to another one please check that and after completion of that then ask for this issue

**Comment by vinit-churi** [comment]
Can I work on this?

**Comment by ayan-biswas0412** [comment]
> I would like to work on this.

yeah go ahead

**Comment by ayan-biswas0412** [comment]
@vinit-churi you have not contributed for a long time in this issue so I am removing you from assignees if you want to still work on this issue please let me know via this thread

**Comment by vinit-churi** [comment]
@ayan-biswas0412  Sorry for the delay, I started working on it today, can I use external CSS for this pages and NavLink or do I have to use the styled components, I will have a pull request by tomorrow.

**Comment by ayan-biswas0412** [comment]
@vinit-churi you can go with styled component no issues

**Comment by vinit-churi** [comment]
https://user-images.githubusercontent.com/39941072/109393140-2fb51400-7946-11eb-9e62-a2c96ee7805e.mp4

@ayan-biswas0412  please see if this satisfies the requirement 
- [x] Add routes for different pages make PageOne.js and PageTwo.js and define their corresponding routes under src/App.js and also integrate React Bootstrap
- [x] all pages should be under src/pages
- [x] show one bootstrap in both of the pages containing text like This is the page one

> this is the file structure I used for pages and components, I have added react-bootstrap to navbar, pageOne and pageTwo

![image](https://user-images.githubusercontent.com/39941072/109393221-7e62ae00-7946-11eb-9d9c-79d33b700db2.png)

**Comment by ayan-biswas0412** [comment]
> 2021-02-27.21-47-01.online-video-cutter.com.mp4 
> 
> @ayan-biswas0412 please see if this satisfies the requirement
> 
> * [x]  Add routes for different pages make PageOne.js and PageTwo.js and define their corresponding routes under src/App.js and also integrate React Bootstrap
> * [x]  all pages should be under src/pages
> * [x]  show one bootstrap in both of the pages containing text like This is the page one
> 
> > this is the file structure I used for pages and components, I have added react-bootstrap to navbar, pageOne and pageTwo
> 
> ![image](https://user-images.githubusercontent.com/39941072/109393221-7e62ae00-7946-11eb-9d9c-79d33b700db2.png)

you should make a PR to get a review on a coding work => but apart from that you must maintain the style of what we have done in the ```hotelontouch``` folder
