### ISSUE TITLE
ADD a CONTRIBUTING.MD file.

### ISSUE THREAD

**Issue by jainaayush01** [ayan-biswas0412/gssoc2021-HotelOnTouch#160]
adding a contributing.md file to the codebase

**Additional context**
It will be helpful for others to know how to contribute to this project.

**Are you working on this? (Yes/No)**
Yes

**Comment by ayan-biswas0412** [comment]
> adding a contributing.md file to the codebase
> 
> **Additional context**
> It will be helpful for others to know how to contribute to this project.
> 
> **Are you working on this? (Yes/No)**
> Yes

we don't need one of this because the project readme is self sufficient
