### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#165]
I am looking for a new maintainer for this project, interested candidates may mail their cv at ayan.biswas@judh.in
with their cv (please only provide your development background)

Mail Subject: Application for Maintainers | HotelOnTouch

### It is not for beginners

**Comment by aniketsingh98571** [comment]
Hey @ayan-biswas0412 Is this issue has been resolved?
