### ISSUE TITLE
Adding a dark mode using toggle button on the landing page.

### ISSUE THREAD

**Issue by GurshehzadSingh** [ayan-biswas0412/gssoc2021-HotelOnTouch#166]
**Is your feature request related to a problem? Please describe.**
Creating a toggle button for adding dark mode on the website

**Describe the solution you'd like**
Adding a button which can change the color of background to black and the text to white when onClick event occurs.

**Are you working on this? (Yes/No)**
Yes

**Comment by ayan-biswas0412** [comment]
> **Is your feature request related to a problem? Please describe.**
> Creating a toggle button for adding dark mode on the website
> 
> **Describe the solution you'd like**
> Adding a button which can change the color of background to black and the text to white when onClick event occurs.
> 
> **Are you working on this? (Yes/No)**
> Yes

it is already developed
