### ISSUE TITLE
Improve footer UI

### ISSUE THREAD

**Issue by akshay1027** [ayan-biswas0412/gssoc2021-HotelOnTouch#172]
**Is your feature request related to a problem? Please describe.**
Improvements we can add to Footer are @ayan-biswas0412  :
1)Find us with logo
2)Call us with logo
3)Mail us with logo
4)Website logo
5)What this website is about
6)Follow us
-Instagram link with logo
-LinkedIn link with logo
-Twitter link with logo
-etc
7)Useful links
-Home
-Services
-About Us
-Contact Us etc
8)Subscribe
-Email address
9)Copyrights
10) All the above with responsive UI

**Are you working on this? (Yes)**

**Comment by ayan-biswas0412** [comment]
go ahead @akshay1027

**Comment by subhangi2731** [comment]
please assign me this
