### ISSUE TITLE
Change layout of the navbar

### ISSUE THREAD

**Issue by rakup444** [ayan-biswas0412/gssoc2021-HotelOnTouch#176]
Move the search bar (in the navbar) to the center.
And make the register, login & contact us buttons on the right side as a legend and remove the SignUp/SignIn menu.

@ayan-biswas0412 
I want to work on this under gssoc'21.

**Comment by subhangi2731** [comment]
please assign me this

**Comment by SainiTej** [comment]
Please assign me this issue @ayan-biswas0412
