### ISSUE TITLE
[GSSOC'21] grammatical errors in the  systemFeature component .

### ISSUE THREAD

**Issue by Tanya933** [ayan-biswas0412/gssoc2021-HotelOnTouch#181]
Grammatical errors like spelling mistakes, missing punctuation marks, etc in the systemFeature component of the homepage.

<img width="1440" alt="Screenshot 2021-04-17 at 13 56 17" src="https://user-images.githubusercontent.com/60508925/115107285-7fe44600-9f87-11eb-8060-393e94a98501.png">

Yes, @ayan-biswas0412  I would like to work on this issue.Please assign this issue to me . Thankyou .

**Comment by KajalSinghBAGHEL** [comment]
Check my pull request
