### ISSUE TITLE
Adding React to the project

### ISSUE THREAD

**Issue by subhangi2731** [ayan-biswas0412/gssoc2021-HotelOnTouch#196]
Add React for front-end development. Setup a simple frontend folder with boilerplate code.

**Comment by subhangi2731** [comment]
please assign me this issue

**Comment by subhangi2731** [comment]
@ayan-biswas0412 can you please assign me this

**Comment by ayan-biswas0412** [comment]
@subhangi2731 i think we are working in react from the beginning what do you want to do ? can you specify ?

**Comment by subhangi2731** [comment]
I was thinking to create a homepage in React and add the content about existing routes and endpoints done in  project. @ayan-biswas0412 Can it be implemented or is any issue open so that I can work on it?

**Comment by subhangi2731** [comment]
@ayan-biswas0412 ?
