### ISSUE TITLE
Adding Menu card in hotel-restaurant-frontend

### ISSUE THREAD

**Issue by kumarishalini6** [ayan-biswas0412/gssoc2021-HotelOnTouch#199]
**Is your feature request related to a problem? Please describe.**
I want to add a Menu Card option in navbar and want to design the as well in hotel-restaurant-frontend side. can i work on this issue under GSSoC'21.

**Comment by bhavita2404** [comment]
Sure. Go ahead

**Comment by bhavita2404** [comment]
But I have seen that you have already opened several issues regarding this. I would suggest you to close the remaining ones and continue working in one PR only.

**Comment by kumarishalini6** [comment]
Please review my PRs
