### ISSUE TITLE
Replacing sign in/sign up dropdown in navbar with sign in, sing up and contact us buttons 

### ISSUE THREAD

**Issue by AbhipsaGuru1012** [ayan-biswas0412/gssoc2021-HotelOnTouch#200]
**Is your feature request related to a problem? Please describe.**
Replacing sign in/sign up dropdown in navbar with sign in, sing up and contact us buttons 

**Describe the solution you'd like**
Replacing sign in/sign up dropdown in navbar with sign in, sing up and contact us buttons 

**Describe alternatives you've considered**

**Additional context**

**Are you working on this? (Yes/No)**
Yes

**Comment by AbhipsaGuru1012** [comment]
@ayan-biswas0412 please let me know if I can work on this issue?

**Comment by bhavita2404** [comment]
This may not look good.
