### ISSUE TITLE
Adding Login Page

### ISSUE THREAD

**Issue by AbhipsaGuru1012** [ayan-biswas0412/gssoc2021-HotelOnTouch#201]
**Is your feature request related to a problem? Please describe.**
Currently the website doesn't have a login page.

**Describe the solution you'd like**
I would like to add a login page

**Describe alternatives you've considered**

**Additional context**

**Are you working on this? (Yes/No)**
Yes

**Comment by bhavita2404** [comment]
Somebody is already working on this issue.
