### ISSUE TITLE
Adding sign up page

### ISSUE THREAD

**Issue by AbhipsaGuru1012** [ayan-biswas0412/gssoc2021-HotelOnTouch#202]
**Is your feature request related to a problem? Please describe.**
Currently the website doesn't have a sign up page

**Describe the solution you'd like**
I would like to add the sign up page

**Describe alternatives you've considered**

**Additional context**

**Are you working on this? (Yes/No)**
Yes

**Comment by bhavita2404** [comment]
Go ahead !!

**Comment by bhavita2404** [comment]
Sorry someone is already working on this issue.
