### ISSUE TITLE
Contact Us Link should be outside the SignUp/SignIn dropdown

### ISSUE THREAD

**Issue by N-Shar-ma** [ayan-biswas0412/gssoc2021-HotelOnTouch#203]
**Describe the bug**
The Contact Us link is inside the dropdown though it is not related to signing up/in

**To Reproduce**

1. Go to 'https://hotelontouch.netlify.app/'
2. See the dropdown in the navbar

**Expected behavior**
Contact Us button / link should be outside the dropdown, screenshot of proposed solution is below:

**Screenshots**
![image](https://user-images.githubusercontent.com/68962290/118177566-b6c34580-b3e7-11eb-82a3-4849c788d22c.png)

**Are you working on this issue? (Yes)**

**Comment by bhavita2404** [comment]
Have you started working on this issue ??

**Comment by bhavita2404** [comment]
have assigned this issue to you. Please give an update on your progress.

**Comment by N-Shar-ma** [comment]
> have assigned this issue to you. Please give an update on your progress.

I'll start working on it right now!
