### ISSUE TITLE
scrollTopButton in home page of hotelontouch

### ISSUE THREAD

**Issue by kumarishalini6** [ayan-biswas0412/gssoc2021-HotelOnTouch#207]
There should be a scroll button at the home page of hotel on  touch. And dark mode button should be at the top.

**Comment by kumarishalini6** [comment]
@ayan-biswas0412  please assign this issue to me, under GSSoC'21.

**Comment by bhavita2404** [comment]
assigned but i think there is no need to put the dark mode button on top.

**Comment by bhavita2404** [comment]
any updates ??
