### ISSUE TITLE
Image not rendering

### ISSUE THREAD

**Issue by Vyomrana02** [ayan-biswas0412/gssoc2021-HotelOnTouch#214]
**Describe the bug**
Bug is under this "We are part of
Girlscript Summer of.."
the image is not rendering

**Expected behavior**
image is should be render cause of tag.

**Screenshots**

![Screenshot 2023-07-09 195022](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/assets/87069619/3791e576-20b6-4ece-b84c-dc89b0cdc6eb)

**Device Information [optional]:**

- OS: [e.g. iOS/Android]

**Additional context**

**Are you working on this issue? (Yes/No)**

**Comment by ManashAnand** [comment]
I want to work on this issue
Please assign this issue to me .
