### ISSUE TITLE
Design a logo for HotelOnTouch

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#22]
**Is your feature request related to a problem? Please describe.**
Read the project description and be creative as much as you can, please attach your logos in this issue and best logo will be taken and shown in the website.Submit your logo in this comment thread

**Comment by rajeshpanjiyar** [comment]
I have made logo for this project, i request you to assign me this work on 1 march 2021.

**Comment by ayan-biswas0412** [comment]
@rajeshpanjiyar welcome to the community 🥰

**Comment by rajeshpanjiyar** [comment]
![image](https://user-images.githubusercontent.com/78999467/108871615-6ecf2680-7621-11eb-98f4-bd78210a666b.png)

Please give feedback i will definitely improve

**Comment by ayan-biswas0412** [comment]
@rajeshpanjiyar it looks good please make the first block a kind of mobile and the second one as tablet or vice versa and also try to make the logo in a round shape

**Comment by rajeshpanjiyar** [comment]
yeah sure, I will do

**Comment by rajeshpanjiyar** [comment]
![image](https://user-images.githubusercontent.com/78999467/108887166-fcb30d80-7631-11eb-850a-45183e8702d1.png)
![image](https://user-images.githubusercontent.com/78999467/108888610-c70f2400-7633-11eb-9071-6e9bddce5d45.png)

I have attached these two. Please give me some feedback

**Comment by ayan-biswas0412** [comment]
@rajeshpanjiyar lets keep the second one and make it pure round and provide a image of a hotel in the Tablet and rest is fine and make the logo base colour as blue

**Comment by rajeshpanjiyar** [comment]
![image](https://user-images.githubusercontent.com/78999467/108895719-10fc0800-763c-11eb-9d4a-cb1ba1ce4a1d.png)

Is this one okay?

**Comment by rajeshpanjiyar** [comment]
![image](https://user-images.githubusercontent.com/78999467/108900459-c087a900-7641-11eb-9288-4e227ede83c0.png)

Or this is required one? Give feedback if some more modification is needed.

**Comment by ayan-biswas0412** [comment]
> ![image](https://user-images.githubusercontent.com/78999467/108895719-10fc0800-763c-11eb-9d4a-cb1ba1ce4a1d.png)
> 
> Is this one okay?

yah this one looks good , now take this and enhance something more , and please raise the font size of Hotel and the Touch text

**Comment by rajeshpanjiyar** [comment]
![image](https://user-images.githubusercontent.com/78999467/108959167-26088380-769c-11eb-9fb8-04869a8662e2.png)

Yeah done

**Comment by ayan-biswas0412** [comment]
> ![image](https://user-images.githubusercontent.com/78999467/108959167-26088380-769c-11eb-9fb8-04869a8662e2.png)
> 
> Yeah done

nice just make the text size a slight bigger and it will be ready

**Comment by rajeshpanjiyar** [comment]
![image](https://user-images.githubusercontent.com/78999467/108987882-e94c8480-76bb-11eb-83d9-4d8c19197170.png)

Yeah text size is bigger now

**Comment by rajeshpanjiyar** [comment]
I will push this logo in a pull request on 1st March,, Will it be fine?

**Comment by Junaid55** [comment]
![20210227_130741_0000](https://user-images.githubusercontent.com/77045046/109388669-8ca4d000-792e-11eb-89dc-be9f8cc8b3b3.png)

**Comment by Junaid55** [comment]
![20210227_180329_0000](https://user-images.githubusercontent.com/77045046/109388688-b0681600-792e-11eb-81f4-4dbd23f9803c.png)

**Comment by Junaid55** [comment]
Animated logo
https://user-images.githubusercontent.com/77045046/109388732-edcca380-792e-11eb-93c1-48e9f483670c.mp4

**Comment by ayan-biswas0412** [comment]
good work @Junaid55 🥰 you can also make one PR once GSSOC coding period starts

**Comment by Junaid55** [comment]
> good work @Junaid55 🥰 you can also make one PR once GSSOC coding period starts

Thanks for your response

**Comment by Junaid55** [comment]
Suggest me one from both of above logo

**Comment by ayan-biswas0412** [comment]
> Suggest me one from both of above logo

I go for the first one , you should make more aesthetic improvements on that and in the animation also

**Comment by shreyanshi16** [comment]
Hey, @ayan-biswas0412 I designed a logo for this project.
![WhatsApp Image 2021-03-08 at 1 02 40 PM](https://user-images.githubusercontent.com/53462278/110307205-a9bf5a00-8024-11eb-8dc2-5f7b7f6bb25e.jpeg)
![WhatsApp Image 2021-03-08 at 1 01 00 PM](https://user-images.githubusercontent.com/53462278/110307209-aaf08700-8024-11eb-88db-8a55a9d0fae8.jpeg)

 Please review it.

**Comment by ayan-biswas0412** [comment]
@shreyanshi16 second one seems very cool

**Comment by shreyanshi16** [comment]
![WhatsApp Image 2021-03-08 at 9 05 22 PM](https://user-images.githubusercontent.com/53462278/110344029-18b3a780-8053-11eb-9c9b-db37248fb99a.jpeg)
@ayan-biswas0412 Please tell me what modification should I make further?

**Comment by ayan-biswas0412** [comment]
> ![WhatsApp Image 2021-03-08 at 9 05 22 PM](https://user-images.githubusercontent.com/53462278/110344029-18b3a780-8053-11eb-9c9b-db37248fb99a.jpeg)
> @ayan-biswas0412 Please tell me what modification should I make further?

please make the colour of the text Hotelontouch  black

**Comment by shreyanshi16** [comment]
![hotelOntouch4](https://user-images.githubusercontent.com/53462278/110366612-8ae4b600-806c-11eb-821e-2ec36dfb8ac7.png)

**Comment by ayan-biswas0412** [comment]
@shreyanshi16 nice now you can make a PR with the last pic , name the file logo_yourusername

**Comment by shreyanshi16** [comment]
Thanks! I will make a PR but can please tell me in which folder I have to add a logo? 
Can I add a logo to hotelontouch/src/assets/ ?

**Comment by ayan-biswas0412** [comment]
> Thanks! I will make a PR but can please tell me in which folder I have to add a logo?
> Can I add a logo to hotelontouch/src/assets/ ?

yes you should
