### ISSUE TITLE
make a Pull request component

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#25]
**Is your feature request related to a problem? Please describe.**
make a component inside ```src/components``` of folder ```hotelontouch``` for showing active PRs of this repository , name the file ```PullRequest.js``` and the function name should be ```PullRequest``` and it should have the following props

1. PR link
2. status = [merged/open/close]
3. based on the status the colour of the component should change [purple/green/red].

also show some sample PRs in a page make a page inside ```src/pages``` and name that ```PullRequest.js```

**Comment by vinit-churi** [comment]
@ayan-biswas0412 I would like to work on these

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 I would like to work on these

sure go ahead

**Comment by vinit-churi** [comment]
@ayan-biswas0412  For these feature, the data of "active PR" should be fetched in homepage and pass PR link and status as props to the PullRequest component right.? 
Should the PullRequest component be similar to Allcontributors component (I mean the card layout and all)

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 For these feature, the data of "active PR" should be fetched in homepage and pass PR link and status as props to the PullRequest component right.?
> Should the PullRequest component be similar to Allcontributors component (I mean the card layout and all)

obviously the layout will not be same it should look like a PR and the colour change is necessary rest of the things you said is ok

**Comment by Muditxofficial** [comment]
@ayan-biswas0412 Can i work on this issue if its available? Also please add labels to my pull request #81

**Comment by subhangi2731** [comment]
please assign me this

**Comment by Muditxofficial** [comment]
@subhangi2731 are you blind ? Can't see he is not replying.                                                                                                          sorry if this looks rude, pin him on discord no reply since 18 days :(

**Comment by subhangi2731** [comment]
@Muditxofficial don't you have manners how to talk to a girl. who are you to talk to me like this first of all you are not admin neither the mentor it's my wish wherever I comment. Have a sense on the language which u are using and the way u are talking.

**Comment by Muditxofficial** [comment]
@subhangi2731 this is my last reply to whatsoever you will say, first of all i asked first to be assigned that means according to rules i should be assigned or unless i say i don't want to. This also means you haven't read gssoc notice and by commenting assign this to me, you have violated that rule. Your 2nd comment is based on gender which is not at all needed.Third point, i have already said sorry on my original comment and by not seeing that you have proved my point. If admin replies you're free to work on this.
