### ISSUE TITLE
make a GitHub status component

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#26]
**Is your feature request related to a problem? Please describe.**
make a component inside ```src/components``` of folder ```hotelontouch``` for showing statuses of this repository , name the file ```GithubStatus.js``` and the function name should be ```GithubStatus``` and it should have the following props

1. Github start
2. Forks
3. Github logo => onClick should redirect to this repo

**Comment by ashirbad29** [comment]
I would like to work on this issue.

**Comment by ayan-biswas0412** [comment]
> I would like to work on this issue.

yeah go ahead

**Comment by ayan-biswas0412** [comment]
@ashirbad29 you have not made contributions in this issue for a long time so I am unassigning you , if you want to still work on this please comment

**Comment by ashirbad29** [comment]
sorry, I am waiting for the GSoC program to start

**Comment by ayan-biswas0412** [comment]
@ashirbad29 GSoC or GSSoc ? 😅

**Comment by ashirbad29** [comment]
I want to work on this issue, can you please assign me again, and what should be the convention for branch names

**Comment by ayan-biswas0412** [comment]
> I want to work on this issue, can you please assign me again, and what should be the convention for branch names

there is no convention till now but please follow the contribution guides

**Comment by ashirbad29** [comment]
do we have any discord servers or groups for more discussion on this issue?

**Comment by ayan-biswas0412** [comment]
> do we have any discord servers or groups for more discussion on this issue?

keep patience @ashirbad29 the official team of GSSoc 2021 will give you all the details shortly
