### ISSUE TITLE
make a wave animation based footer

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#28]
**Is your feature request related to a problem? Please describe.**
make a component inside ```src/components``` of folder ```hotelontouch``` , name the file ```Footer.js``` and the function name should be ```Footer``` and it should have the link to the the Github Repository

Make the footer which looks nice, new and creative ideas are most welcome

**Comment by aniketsingh98571** [comment]
Hey, can I take up this issue for GSSoC 2021? @ayan-biswas0412

**Comment by ayan-biswas0412** [comment]
> Hey, can I take up this issue for GSSoC 2021? @ayan-biswas0412

you can work on this issue but I can merge your PR on or after 1 March for the consideration for GSSoc 2021

**Comment by aniketsingh98571** [comment]
yeah it's totally fine!!

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412  What will be the color theme of the website, so that I can be picky about the footer colors. And I didn't
got this point `it should have the link to the the Github Repository`.

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 What will be the color theme of the website, so that I can be picky about the footer colors. And I didn't
> got this point `it should have the link to the the Github Repository`.

you can go with some colours around blue and for the second part there should be a GitHub icon which points to this repository

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 Should I raise a PR after 1 march?

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 Should I raise a PR after 1 march? I have setup the project on my machine and will start working on the footer from today,

you may raise PR and I can merge it after March 1

**Comment by aniketsingh98571** [comment]
can we use css for syting @ayan-biswas0412 . If yes what will be folder structure then?

**Comment by aniketsingh98571** [comment]
Can I use `npm eject` for using CSS modules?

**Comment by ayan-biswas0412** [comment]
@aniketsingh98571 you may use [styled-components](https://styled-components.com) and you can use them in same file - no need to change the folder structure

**Comment by ayan-biswas0412** [comment]
> Can I use `npm eject` for using CSS modules?

no

**Comment by aniketsingh98571** [comment]
> @aniketsingh98571 you may use [styled-components](https://styled-components.com) and you can use them in same file - no need to change the folder structure

Ok got it.

**Comment by aniketsingh98571** [comment]
> @aniketsingh98571 you may use [styled-components](https://styled-components.com) and you can use them in same file - no need to change the folder structure

means I need to it install it right `npm install --save styled-components`

**Comment by ayan-biswas0412** [comment]
> > @aniketsingh98571 you may use [styled-components](https://styled-components.com) and you can use them in same file - no need to change the folder structure
> 
> means I need to it install it right `npm install --save styled-components`

yes

**Comment by aniketsingh98571** [comment]
![Screenshot (109)](https://user-images.githubusercontent.com/63097956/108632714-5ed70b80-7496-11eb-88d8-a3f2dabb4e57.png)
@ayan-biswas0412  Is this footer satisfies your requirements, don't worry about styling, I am working on it.

**Comment by ayan-biswas0412** [comment]
> ![Screenshot (109)](https://user-images.githubusercontent.com/63097956/108632714-5ed70b80-7496-11eb-88d8-a3f2dabb4e57.png)
> @ayan-biswas0412 Is this footer satisfies your requirements, don't worry about styling, I am working on it.

yeah nice it is a good start , make more style improvements

**Comment by aniketsingh98571** [comment]
ok sure, I am working on styling don't.

**Comment by aniketsingh98571** [comment]
![Mobile](https://user-images.githubusercontent.com/63097956/108736773-edf82800-7557-11eb-9f0e-9ab1e17bd092.png)
![laptop](https://user-images.githubusercontent.com/63097956/108736796-f2bcdc00-7557-11eb-8487-4072495bff63.png)
@ayan-biswas0412, Have a look at the footer section at different devices. Is it fine?

**Comment by ayan-biswas0412** [comment]
@aniketsingh98571 please keep the GitHub icon only and integrate the **wave animation**  for the different device aspect it is fine for now

**Comment by aniketsingh98571** [comment]
> @aniketsingh98571 please keep the GitHub icon only and integrate the **wave animation** for the different device aspect it is fine for now

only github icon will not look good, but then also I will keep it and regarding the wave animation it will be complex work but I will try.

**Comment by ayan-biswas0412** [comment]
> > @aniketsingh98571 please keep the GitHub icon only and integrate the **wave animation** for the different device aspect it is fine for now
> 
> only github icon will not look good, but then also I will keep it and regarding the wave animation it will be complex work but I will try.

use this for wave animation https://www.npmjs.com/package/react-wavify/v/1.2.1

**Comment by aniketsingh98571** [comment]
https://user-images.githubusercontent.com/63097956/108808940-cc398800-75cd-11eb-85cc-6f638311e4af.mp4

@ayan-biswas0412  Here I have integrated wave animation via `react-wavify`.Is it fine?

**Comment by ayan-biswas0412** [comment]
@aniketsingh98571 yah it seems fine just change the frequency of the wave and increase it little bit and make a PR I will review it

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412  created a PR. Have a look.

**Comment by batman005** [comment]
https://user-images.githubusercontent.com/51878340/108825703-5a6f3780-75e9-11eb-8f55-672e8a0e19c2.mp4

@ayan-biswas0412  I have also made  an  wave animation based footer .please have a look  into it...

**Comment by ayan-biswas0412** [comment]
@batman005 it is good but as it was assigned to @aniketsingh98571 so we will give priority first to his work but you can also enhance this and make a PR we will review it and maybe we can take it for another website anyways Good Work

**Comment by batman005** [comment]
Okay sir , thankyouu

**Comment by aniketsingh98571** [comment]
https://user-images.githubusercontent.com/63097956/108883581-a04cef80-762b-11eb-846c-21f0076e9085.mp4

@ayan-biswas0412  Is it fine now?

**Comment by ayan-biswas0412** [comment]
yah I think @aniketsingh98571 it is fine please update your PR also

**Comment by ayan-biswas0412** [comment]
@batman005 can you make your PR also

**Comment by batman005** [comment]
@ayan-biswas0412  okay sure
