### ISSUE TITLE
make All contributors section in main website

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#35]
**Is your feature request related to a problem? Please describe.**
make a component inside ```src/components``` of folder ```hotelontouch``` , name the file ```AllContributors.js``` and the function name should be ```AllContributors``` and it should show the following information

1. Contributor Github Profile image
2. Github username => Clickable => Redirect to their profile
3. All contributors should be arranged in a way that old contributors remains on top
4. Component should be responsive to screen size

Render the component in HomeScreen
Use Github API to fetch the list of contributors of this repository
See the [website](https://doc2pen.smaranjitghose.codes) they have a contributors section

**Comment by vinit-churi** [comment]
@ayan-biswas0412  can I work on these.

**Comment by ayan-biswas0412** [comment]
@vinit-churi go ahead

**Comment by vinit-churi** [comment]
@ayan-biswas0412 can I use react-query? github provides both REST and GraphQL api , which one should be used in this project?

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 can I use react-query? github provides both REST and GraphQL api , which one should be used in this project?

you can use any of them as per your convinience
