### ISSUE TITLE
Add cool svgs and make a section which describes the entire project 

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#36]
**Is your feature request related to a problem? Please describe.**
Read the project description from Readme and make one component ```AboutProject.js``` inside ```src/components``` in the folder ```hotelontouch``` which describes the entire project, use your own words , you can use cool animations or svgs to describe the project well.

Innovative ideas are most welcome

**Comment by ayan-biswas0412** [comment]
@rajeshpanjiyar yah please finalise your previous task and I will assign this to you after that

**Comment by ayan-biswas0412** [comment]
@rajeshpanjiyar so the logo is fine for now you can make PR on 1st march and I am assigning this to you now

**Comment by rajeshpanjiyar** [comment]
Due to some other reason, I removed myself from this. Please pardon me!

**Comment by ShyrenMore** [comment]
Hello, could you please assign me this issue, I need 15-20 days for making this

**Comment by ayan-biswas0412** [comment]
> Hello, could you please assign me this issue, I need 15-20 days for making this

I think 15-20 days is soo long

**Comment by ShyrenMore** [comment]
hey @ayan-biswas0412 I am halfway through making the about page, however, I can't introduce routing, in which file am I suppose to use Link, Switch and Router component?

**Comment by ayan-biswas0412** [comment]
> hey @ayan-biswas0412 I am halfway through making the about page, however, I can't introduce routing, in which file am I suppose to use Link, Switch and Router component?

in App.js
