### ISSUE TITLE
Make a Project Admin Card Component 

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#37]
**Is your feature request related to a problem? Please describe.**
Add a project admin card component the card should contain 
Project Admin Name : Ayan Biswas , Github Username : ayan-biswas0412 , Website : https://ayanbiswas.in and fetch the GitHub profile picture for the card

Name the component ```AdminCard.js``` , keep this in ```hotelontouch/src/components``` and render it in ```HomePage.js```

**Describe the solution you'd like**
Use React Bootstrap Cards and make a good looking card  
Innovative ideas are most welcome

**Comment by Doringl** [comment]
I can do that if you want ?

**Comment by Doringl** [comment]
And if you want to convert project to TypeScript i can help you too ...

**Comment by ayan-biswas0412** [comment]
@Doringl go ahead

**Comment by ayan-biswas0412** [comment]
> And if you want to convert project to TypeScript i can help you too ...

Thank you again @Doringl for your interest but at this time we want to go with javascript only
