### ISSUE TITLE
Make Contact us form

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#38]
**Is your feature request related to a problem? Please describe.**
Make one blank contact us form which takes the following inputs
1.Name 
2. Email
3. Message

**Describe the solution you'd like**
Make the component inside ```hotelontouch/src/components``` and name the component ```ContactUs.js``` the component should be good looking , more innovative ideas are welcome

**Additional context**
Use React Bootstrap Forms and give proper validation checks , ignore the form action part for now there should be blank action url for POST Request of the json , for now after form submit show the json in ```console.log```

**Comment by khareyash05** [comment]
Hi! I would like to work on it as a part of GSSOC'21

**Comment by ayan-biswas0412** [comment]
@khareyash05 sure but make sure you follow all the guidelines of GSSoc 2021

**Comment by Doringl** [comment]
Can i help you ?

**Comment by code-gidi** [comment]
Is this project under GSoC2021?

**Comment by ayan-biswas0412** [comment]
> Is this project under GSoC2021?

no it is not under GSoC 2021

**Comment by Doringl** [comment]
I will handle it.

**Comment by ayan-biswas0412** [comment]
@Doringl good work and I have given some reviews , and please be patient , after assigning in an issue please make your PR but till then please be patient

**Comment by shreyanshi16** [comment]
Is the issue has been solved? If no then can I work on this issue if no one is working?

**Comment by ayan-biswas0412** [comment]
> Is the issue has been solved? If no then can I work on this issue if no one is working?

sure

**Comment by shreyanshi16** [comment]
Hi @ayan-biswas0412, Please review my PR and let me know if there are any changes required.
