### ISSUE TITLE
make open source section in the website

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#39]
**Is your feature request related to a problem? Please describe.**
Make one component open source programmes we are part of which can take a json as props the json should be as below
```js
let openSource = [
{
"name" : "Girlscript Summer of Code 2021",
"url" :"gesso.tech",
"logo" : "logo_url" // either from web or imported locally
}
]
```

**Describe the solution you'd like**
the component should be under ```hotelontouch/src/components``` and should be named ```OpensourceProgramme.js```

**Additional context**
You can use React Bootstrap Cards

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 I can go ahead with this...

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 I can go ahead with this...

sure.

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 , what to do for the images because extracting from the web is not feasible and also if we try to upload it on Github and then use it, then also it will not work and do you want any information to be displayed on the card besides, logo, name, and URL. The logo is to be provided as an image inside the card?

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 , what to do for the images because extracting from the web is not feasible and also if we try to upload it on Github and then use it, then also it will not work and do you want any information to be displayed on the card besides, logo, name, and URL. The logo is to be provided as an image inside the card?

download the images and save in assets folder and import them as needed, for now as I have described above make the card like that and do PR then I will review

**Comment by aniketsingh98571** [comment]
https://user-images.githubusercontent.com/63097956/109142597-131dae00-7785-11eb-9b17-07e1ba1ad3ae.mp4

@ayan-biswas0412  Is this fine? Works on all aspect devices. Regarding the images, we have to just provide the relative path of image in the `logo` .

**Comment by ayan-biswas0412** [comment]
> HotelOnTouch.-.Google.Chrome.2021-02-25.16-16-31.mp4 
> 
> @ayan-biswas0412 Is this fine? Works on all aspect devices. Regarding the images, we have to just provide the relative path of image in the `logo` .

yeah fine just increase the spacing between the cards
