### ISSUE TITLE
make a login page in hotel-admin-frontend

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#43]
**Is your feature request related to a problem? Please describe.**
make one login page inside ```hotel-admin-frontend/src/pages``` and name it ```Login.js``` use React Bootstrap forms
there should be the following fields

1.Username
2.Password
3.Captcha Validation
4. Proper validation check for Valid Email formats in the ```Username``` Field
5. If captcha is not done then form can't be submitted 
6. On Successful submission print the formdata in consul.log

**Comment by Sapna2001** [comment]
@ayan-biswas0412 can I work on this as a part of GSSOC 2021. Plz, assign me this issue I will start working on this when the contribution period starts.

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 can I work on this as a part of GSSOC 2021. Plz, assign me this issue I will start working on this when the contribution period starts.

you can Start working and make the PR on march 1

**Comment by GurshehzadSingh** [comment]
im a gssoc participant and i would like to work on this isuue.

**Comment by GurshehzadSingh** [comment]
Making a PR in a few hours.

**Comment by subhangi2731** [comment]
please assign me this. I will make a pr by tomorrow
