### ISSUE TITLE
Study the file structure in src and document the development guide 

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#44]
**Is your feature request related to a problem? Please describe.**
Edit the ```Readme.md``` in the https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/tree/main/hotelontouch but first please study the whole flow and try to run using yarn start and then study the folder structure we use and the function naming types and document the whole thing in Readme.md such that a new developer can easily understand the codebase.

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412, I can go with this issue.

**Comment by ayan-biswas0412** [comment]
@aniketsingh98571 after completion of your previous task please let me know then i will assign you here

**Comment by aniketsingh98571** [comment]
> @aniketsingh98571 after completion of your previous task please let me know then i will assign you here

ok sure

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 can I go with this now?

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 can I go with this now?

sure

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412  Should I replace all the contents inside `readme.md` of `hotelontouch` with my contents.

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 Should I replace all the contents inside `readme.md` of `hotelontouch` with my contents.

yah

**Comment by aniketsingh98571** [comment]
![Screenshot (117)](https://user-images.githubusercontent.com/63097956/109529306-9d467900-7adb-11eb-97cc-450208c88190.png)
@ayan-biswas0412  Is it fine?

**Comment by ayan-biswas0412** [comment]
> ![Screenshot (117)](https://user-images.githubusercontent.com/63097956/109529306-9d467900-7adb-11eb-97cc-450208c88190.png)
> @ayan-biswas0412 Is it fine?

setting up project and how to contribute section is not needed we need only the technical structure of the project starting from ```index.js``` and if you give a folder structure that would be better and don't explain the components only explain the pages also and how to export in ```components/index.js``` and ```pages/index.js```

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412  I will add the folder structure too, but I advice you to keep `setting up` and `how to contribute` section also as it will help beginners who don't have any knowledge in reactjs.

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 I will add the folder structure too, but I advice you to keep `setting up` and `how to contribute` section also as it will help beginners who don't have any knowledge in reactjs.

Thank you for your suggestion actually there is a separate guide for that you can [link](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/wiki/Setup-React-App) this in your documentation

**Comment by aniketsingh98571** [comment]
Okay got it, and also it would be great if you could add GSSoC label also for PR's and issues with their difficulty level as it will help mentors to allot points as well as look for only GSSoC related PR and issues.

**Comment by ayan-biswas0412** [comment]
> Okay got it, and also it would be great if you could add GSSoC label also for PR's and issues with their difficulty level as it will help mentors to allot points as well as look for only GSSoC related PR and issues.

yah sure we will do that , just waiting for the official instructions from GSSoc regarding that

**Comment by aniketsingh98571** [comment]
![Screenshot (123)](https://user-images.githubusercontent.com/63097956/109680872-ec0b1600-7ba2-11eb-92e5-30e3f12cbe52.png)
@ayan-biswas0412  Is it fine now?

**Comment by aniketsingh98571** [comment]
I have provided the links to the particular sections,

**Comment by ayan-biswas0412** [comment]
> ![Screenshot (123)](https://user-images.githubusercontent.com/63097956/109680872-ec0b1600-7ba2-11eb-92e5-30e3f12cbe52.png)
> @ayan-biswas0412 Is it fine now?

it looks good but please make a PR then only I can give you actual review

**Comment by aniketsingh98571** [comment]
ok raising the PR now..

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 Check it

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 Check it

yes I have given my review please resolve those
