### ISSUE TITLE
Setup an authstack navigator in hotel-admin-frontend

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#47]
**Is your feature request related to a problem? Please describe.**
make two sample routes ```Home.js``` and ```Dashboard.js``` and setup the authentication navigator for now just define authState by hardcoding userState say ``loggedIn``` and ```loggedOut``` and based on that Home should be accessed in both modes but dashboard can only be accessed in logged in mode

**Comment by vinit-churi** [comment]
by authentication navigation do you mean, there should be a home and dashboard nav-menu-item along with login button on navbar  with hard coded functionality that when the user clicks on it the userState will become loggedln and he can access the protected route that is dashboard?

**Comment by ayan-biswas0412** [comment]
@vinit-churi yes and you can also use useEffect hook to handle the signing flow like for now keep a functiontion signIn () which returns loggedin state after 5 secs and for this 5 secs the loading spinner should be visible

**Comment by subhangi2731** [comment]
can you please assign it to me?

**Comment by ayan-biswas0412** [comment]
please work on a single issue @subhangi2731 first submit a PR for your assigned work then only I can assign you here

**Comment by samyakjain10** [comment]
Hey! I want to work on this issue under GSSOC'21. Can you assign this issue to me??

**Comment by samyakjain10** [comment]
@ayan-biswas0412 Sir i am unable to figure out where the feature needs to be added. Can you explain in detail??

**Comment by samyakjain10** [comment]
Sorry. I am unable to complete the given task!

**Comment by subhangi2731** [comment]
Hello @ayan-biswas0412 in this do we have to create the stack navigator and do the whole authentication setup?

**Comment by ayan-biswas0412** [comment]
> Hello @ayan-biswas0412 in this do we have to create the stack navigator and do the whole authentication setup?

yes but you can mock the authentication part just by creating a function login() and return true always

**Comment by ayan-biswas0412** [comment]
> > Hello @ayan-biswas0412 in this do we have to create the stack navigator and do the whole authentication setup?
> 
> yes but you can mock the authentication part just by creating a function login() and return true always and a
