### ISSUE TITLE
setup react-native paper in customerfrontend app

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#48]
**Is your feature request related to a problem? Please describe.**
Setup the React native paper theming in the customer frontend app you can take help from https://callstack.github.io/react-native-paper/

**Comment by subhangi2731** [comment]
can you please assign it to me?

**Comment by ayan-biswas0412** [comment]
sure @subhangi2731

**Comment by ayan-biswas0412** [comment]
@subhangi2731 are you working ?
