### ISSUE TITLE
make a feature section in main website

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#50]
**Is your feature request related to a problem? Please describe.**
make a component ```SystemFeature.js```  inside ```hotelontouch``` and provide a proper svg from undraw and write one heading ```Completely Open Sourced Hotel Management System```` and under that add the project description by copying from Readme.

**Comment by nlok5923** [comment]
please can you assign this issue to me i would like to work on it.

**Comment by ayan-biswas0412** [comment]
@nlok5923  sure go ahead

**Comment by ayan-biswas0412** [comment]
@nlok5923 are u working ?

**Comment by ayan-biswas0412** [comment]
@abhishek7997 wait for @nlok5923 if he is not working then go ahead

**Comment by nlok5923** [comment]
@ayan-biswas0412 you can assign @abhishek7997 on it as currently I am.busy somewhere else.

**Comment by abhishek7997** [comment]
Should SystemFeature.js be created just inside hotelontouch or hotelontouch/src/components ?

**Comment by ayan-biswas0412** [comment]
> Should SystemFeature.js be created just inside hotelontouch or hotelontouch/src/components ?
> Should the feature page be a comletely separate page, or will it be just under the home page (welcome Page)?

it will be under homepage and as your said the feature will reside in hotelontouch or hotelontouch/src/components

**Comment by abhishek7997** [comment]
Okay

**Comment by abhishek7997** [comment]
By home page, do you mean it should be under the jumbotron component or the Allcontributors component?

**Comment by abhishek7997** [comment]
Is this configuration correct ?

![image](https://user-images.githubusercontent.com/68701271/110509086-bbd5f100-8127-11eb-9ed5-2b2fc44205a3.png)

**Comment by abhishek7997** [comment]
![image](https://user-images.githubusercontent.com/68701271/110512023-d78ec680-812a-11eb-8a90-e834e5fbf827.png)

This is the updated one with svg

**Comment by abhishek7997** [comment]
Is the new configuration with svg image file correct?

**Comment by ayan-biswas0412** [comment]
> ![image](https://user-images.githubusercontent.com/68701271/110512023-d78ec680-812a-11eb-8a90-e834e5fbf827.png)
> 
> This is the updated one with svg

kindly mention this in PR not in issues

**Comment by abhishek7997** [comment]
I have made the PR, but how do I create and add a link to the updated website? Netlify is giving error.

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412
> I have made the PR, but how do I create and add a link to the updated website? Netlify is giving an error.

given a review kindly go through that
