### ISSUE TITLE
Readme netlify badge error

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#51]
**Describe the bug**
In the Readme, the netlify badges are showing the statuses of the last build (be it a PR preview deploy or a production main branch deploy ) but the expected behavior is it must show the latest main branch build status only

**To Reproduce**

1. Go to Readme.md

**Expected behavior**
Only show the main branch deploy status

**Screenshots**
![image](https://user-images.githubusercontent.com/52851184/109283986-62c3ae80-7845-11eb-9ade-4c8ad94d2d9c.png)

**Comment by san0808** [comment]
can you describe the bug more

**Comment by ayan-biswas0412** [comment]
> can you describe the bug more

actually these badges are showing the status of the latest build that happened (be it a CI check or it is a main branch build) but I want only the main branch build status to be shown here

**Comment by san0808** [comment]
<img width="427" alt="Screenshot 2021-03-07 100842" src="https://user-images.githubusercontent.com/72181610/110229132-2e2eb180-7f2d-11eb-8e73-0e5535d8fa27.png">
i tried checking for settings but i think only the person who deployed can change it

**Comment by san0808** [comment]
check this website for more info https://docs.netlify.com/site-deploys/overview/
check for site ->overview->then branch deploy settings

**Comment by ayan-biswas0412** [comment]
> check this website for more info https://docs.netlify.com/site-deploys/overview/
> check for site ->overview->then branch deploy settings

Thanks I will surely look into it

**Comment by san0808** [comment]
is this a part of functioning in gssoc21 ?
//since it is my first time working properly in open source i was simply asking //

**Comment by ayan-biswas0412** [comment]
> is this a part of functioning in gssoc21 ?
> //since it is my first time working properly in open source i was simply asking //

the thing you specified already I have done that before but still the error is there in Readme

**Comment by SrirajBehera** [comment]
can i work in this issue? I am GSSOC 21 participant.

**Comment by ayan-biswas0412** [comment]
> can i work in this issue if it is available? I am GSSOC 21 participant.

you can but we have yet not decided that if this issue is workable or not

**Comment by Varun8216889** [comment]
As a beginner, I want to contribute but I am not able to find the issue.
Can I start my contribution by working on this issue under GSSoC'21? Kindly assign it to me or suggest me one.

**Comment by ayan-biswas0412** [comment]
> As a beginner, I want to contribute but I am not able to find the issue.
> Can I start my contribution by working on this issue under GSSoC'21? Kindly assign it to me or suggest me one.

sure

**Comment by Varun8216889** [comment]
@ayan-biswas0412 I am stuck.
I don't know how this process should run I tried many times but it still giving the same error. plz help through a specified path
