### ISSUE TITLE
Add a try good first issue section in main website

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#52]
**Is your feature request related to a problem? Please describe.**
Add a button in the main website which will have link to all the good first issues of this repository , show your creative work you may use svgs to make it cool , more innovative ideas are welcome feel free to suggest design

**Comment by khareyash05** [comment]
Hi! I would like to work on this issue as a part of GSSOC'21.

**Comment by nlok5923** [comment]
i would like to work on it please assign it to me.

**Comment by ayan-biswas0412** [comment]
@nlok5923 you can work on a single issue at a time please complete your previously assigned issue then comment here I will then assign you

**Comment by khareyash05** [comment]
Hey I would like to work on this issue under GSSOC'21

**Comment by ayan-biswas0412** [comment]
> Hey I would like to work on this issue under GSSOC'21

You can work but I can merge your PR on or after 8th March

**Comment by dhruvinfo28** [comment]
I'd like to contribute for this under GSSOC'21. Kindly assign me.

**Comment by SrirajBehera** [comment]
I want to contribute to this issue. I am a GSSOC 21 Participant.

**Comment by shreyanshi16** [comment]
I would like to work on this issue under GSSOC'21, could I?

**Comment by ayan-biswas0412** [comment]
@shreyanshi16 @SrirajBehera @dhruvinfo28 you can try to make good designs also in this issue most innovative solution wil be taken

**Comment by shreyanshi16** [comment]
@ayan-biswas0412 Here is my designs for a good first issue section:

![design1](https://user-images.githubusercontent.com/53462278/110762697-16ca2e00-8277-11eb-9078-34b4925dd5b7.png)
![design2](https://user-images.githubusercontent.com/53462278/110762706-1893f180-8277-11eb-8d91-c7d0b5f0be35.png)

Tell me if you like any of the designs.

**Comment by ayan-biswas0412** [comment]
@shreyanshi16 first one seems cool can you implement in code and make a PR
