### ISSUE TITLE
Add our Solutions Section in the main website

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#55]
**Is your feature request related to a problem? Please describe.**
make the component inside ```hotelontouch/src/components``` , Give the name ```OurSolution.js``` and use good svgs and small description (refer Readme) about the three project modules 

1. Hotel Guest App 
2. Hotel Admin App 
3. Hotel Services End App

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 Actually what we have to do for this issue, I am not getting it.

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 Actually what we have to do for this issue, I am not getting it.

actually you have to make three cards which have some cool svgs (you can take them from undraw or whatever you want) and the three cards should be mobile responsive and they should be rendered in homepage

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 What information to be included in the card?

**Comment by aniketsingh98571** [comment]
Is this issue the same as #42 ?

**Comment by aniketsingh98571** [comment]
I would like to go with it, just explain to me the answers to the above questions?

**Comment by ayan-biswas0412** [comment]
> I would like to go with it, just explain to me the answers to the above questions?

yah sorry for the duplication it is same but go with this issue not #42 i will close that

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 can you assign it to me?

**Comment by ayan-biswas0412** [comment]
sure @aniketsingh98571

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 Is there any need to add buttons also to cards. for redirection into a particular section?

**Comment by aniketsingh98571** [comment]
![Screenshot (124)](https://user-images.githubusercontent.com/63097956/111022568-70f2fc80-83f9-11eb-8cbe-26b1de0cfd30.png)
This is what I have done uptill now, Is this SVG fine, and do I need to replace the button with some text?

**Comment by ayan-biswas0412** [comment]
> ![Screenshot (124)](https://user-images.githubusercontent.com/63097956/111022568-70f2fc80-83f9-11eb-8cbe-26b1de0cfd30.png)
> This is what I have done uptill now, Is this SVG fine, and do I need to replace the button with some text?

great but please change the svgs because three of them seems very closely related line you have to distinguish between (guest/admin and services) please make PR to get quick review
