### ISSUE TITLE
Add this label at the start of the Readme

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#57]
**Is your feature request related to a problem? Please describe.**

[![CodeFactor](https://www.codefactor.io/repository/github/ayan-biswas0412/gssoc2021-hotelontouch/badge)](https://www.codefactor.io/repository/github/ayan-biswas0412/gssoc2021-hotelontouch)

Just copy the below text to get the label
```
[![CodeFactor](https://www.codefactor.io/repository/github/ayan-biswas0412/gssoc2021-hotelontouch/badge)](https://www.codefactor.io/repository/github/ayan-biswas0412/gssoc2021-hotelontouch)
```
Add it at the first of the Readme file

**Comment by tanay13** [comment]
Please assign this to me

**Comment by ayan-biswas0412** [comment]
sure @tanay13
