### ISSUE TITLE
Add a title project admin

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#69]
**Is your feature request related to a problem? Please describe.**
Add a title project admin before the picture of the project admin edit the ```hotelontouch/src/components/AdminCard.js```
and make UI improvement of the card if possible more interactive designs are welcome

**Comment by Ruchip16** [comment]
Can I work on this issue ?

**Comment by ayan-biswas0412** [comment]
@Ruchip16 sure go ahead

**Comment by Ruchip16** [comment]
thanks @ayan-biswas0412

**Comment by Ruchip16** [comment]
@ayan-biswas0412 does this project has contributing guidelines?

**Comment by Ruchip16** [comment]
@ayan-biswas0412  in admin card where do we need to add title ?

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 in Admincard.js where do we need to add the title " Project Admin"?

in the card itself

**Comment by Ruchip16** [comment]
onst AdminCard = ({
  projectAdminName = 'Ayan Biswas',
  GitHubUserName = 'ayan-biswas0412',
  webSite = 'https://ayanbiswas.in',
}) => {
  return (
    <StyledCardContainer>
      <StyledCard border='primary'>
        <StyledImage
          variant='top'
          src={`https://avatars.githubusercontent.com/${GitHubUserName}`}
        />
        <Card.Body>
          <Card.Title style={{ textAlign: 'center' }}>
            {projectAdminName}
          </Card.Title>``

**Comment by ayan-biswas0412** [comment]
> onst AdminCard = ({
> projectAdminName = 'Ayan Biswas',
> GitHubUserName = 'ayan-biswas0412',
> webSite = 'https://ayanbiswas.in',
> }) => {
> return (
> 
> 
> <StyledImage
> variant='top'
> src={`https://avatars.githubusercontent.com/${GitHubUserName}`}
> />
> <Card.Body>
> <Card.Title style={{ textAlign: 'center' }}>
> {projectAdminName}
> </Card.Title>``

make a pr then only I can give your review

**Comment by Ruchip16** [comment]
I am not able to understand that do I need to add a const render card? like the one you added in opensourceprogramme.js to add title we are a part of ?

**Comment by Ruchip16** [comment]
@ayan-biswas0412  I have created a PR check once , plz merge it and give PR for review I will do the necessary changes

**Comment by Ankita297** [comment]
Can i work on this ? @ayan-biswas0412

**Comment by Ankita297** [comment]
@ayan-biswas0412

**Comment by Ankita297** [comment]
@ayan-biswas0412  you have assign the ui design of card   issue to someone ? So should i only change the title ?
