### ISSUE TITLE
Make responsive navbar 

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#70]
**Is your feature request related to a problem? Please describe.**
The current navbar in the website is kind of old age type, make it such that it look good 
edit the ```hotelontouch/src/components/NavbarComponent.js```

**Comment by Muditxofficial** [comment]
@ayan-biswas0412 please assign this to me

**Comment by ayan-biswas0412** [comment]
@Muditxofficial yeah sure

**Comment by Ruchip16** [comment]
Can I work on this issue?

**Comment by ayan-biswas0412** [comment]
> Can I work on this issue?

see one is already assigned in this you are requested to see other issues

**Comment by Muditxofficial** [comment]
![navbar](https://user-images.githubusercontent.com/63860014/110412093-a625e480-80b1-11eb-9f6d-983d3e04f50e.png)
Is this good enough ?

**Comment by ayan-biswas0412** [comment]
> ![navbar](https://user-images.githubusercontent.com/63860014/110412093-a625e480-80b1-11eb-9f6d-983d3e04f50e.png)
> Is this good enough ?

yeah looks good just change the colour to match site theme
