### ISSUE TITLE
Enhance the Welcome to project section

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#71]
**Is your feature request related to a problem? Please describe.**
Enhance the Welcome component add some cool svgs make responsive design if possible show your creativity, good animated designs are most welcome

**Comment by padmajabhol** [comment]
Hello, I m interested to contribute in this particular issue, will be glad if you assign me this.

**Comment by ayan-biswas0412** [comment]
yeah sure @padmajabhol

**Comment by padmajabhol** [comment]
@ayan-biswas0412 Hello, I have sent the PR.

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 Hello, I have sent the PR.

see I have given some comments there

**Comment by sayna3311** [comment]
I would love to work on this issue. Please, assign this to me :)

**Comment by farseenmanekhan1232** [comment]
I would love to work on this issue . Please assign me.

**Comment by ayan-biswas0412** [comment]
> I would love to work on this issue . Please assign me.

you are already assigned to another issue

**Comment by Ankita297** [comment]
Can i work on this ? @ayan-biswas0412
