### ISSUE TITLE
Enhance the We are a part of section

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#72]
**Is your feature request related to a problem? Please describe.**
1. Enlarge the text size of the We are a part of 
2. Make style improvements in the section, use some cool animations if possible

**Comment by Ankita297** [comment]
Can i  work on this issue ?

**Comment by rajeshpanjiyar** [comment]
@Ankita297, I am already working on this. If you don't mind can I continue towards the pull request?

**Comment by ayan-biswas0412** [comment]
@aniketsingh98571 if you are in midway you can also make a PR (it is up to you) but as @Ankita297 has requested before so we will give preference to her.

**Comment by Ankita297** [comment]
![HotelOnTouch - Google Chrome 12-03-2021 19_15_43](https://user-images.githubusercontent.com/67833077/110948486-6851e600-8367-11eb-96ba-35206469ea80.png)

**Comment by Ankita297** [comment]
Sir is it okay ?

**Comment by ayan-biswas0412** [comment]
> Sir is it okay ?

please make PR then only I can give you a proper review otherwise the design is ok

**Comment by Ankita297** [comment]
okay Sir .
