### ISSUE TITLE
go to wiki addition

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#73]
**Is your feature request related to a problem? Please describe.**

Add a line at the end of the Readme , ```Go the the Wiki for more info```
and give this like as [Click Here](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/wiki)

**Comment by Anjali041** [comment]
Please assign it to me as a part of Gssoc'21

**Comment by ayan-biswas0412** [comment]
sure @Anjali041
