### ISSUE TITLE
typo in config.yml

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#76]
https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/blob/bcfd5264ca7a0517c9ba46069d54f6eb18ed1088/.github/config.yml#L15

change the line to : you can find different issues
check there is a typo

**Comment by Anjali041** [comment]
Please assign this to me.

**Comment by ayan-biswas0412** [comment]
sure @Anjali041
