### ISSUE TITLE
Move Items in the Navbar to center

### ISSUE THREAD

**Issue by JanviMahajan14** [ayan-biswas0412/gssoc2021-HotelOnTouch#83]
**Describe the bug**
On resizing the screen in the main [website](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/tree/main/hotelontouch) HotelOnTouch the Home section in the navbar aligns to left. We want to align the text in the center.

**Steps to reproduce**
1. Run the HotelOnTouch module locally on the system.
2. Resize the window
4. See the bug in the Navbar for the Home section.

**Expected behavior**
![Screenshot from 2021-03-09 17-54-39](https://user-images.githubusercontent.com/46385227/110470892-6e468d80-8101-11eb-8a15-3ae29b4671a2.png)

**Comment by JanviMahajan14** [comment]
Sure @san0808 . Go for it :)

**Comment by SARVESHKHANDELWAL** [comment]
Hello @ayan-biswas0412 ,
Can i work on this issue.

**Comment by ayan-biswas0412** [comment]
@SARVESHKHANDELWAL please wait we will be opening few new issues very soon , already one person is assigned in this issue

**Comment by SARVESHKHANDELWAL** [comment]
Okyy @ayan-biswas0412

**Comment by Ankita297** [comment]
@ayan-biswas0412  Can i work on this ?
