### ISSUE TITLE
Adding a Favicon in the title bar

### ISSUE THREAD

**Issue by JanviMahajan14** [ayan-biswas0412/gssoc2021-HotelOnTouch#84]
**Module**: HotelOnTouch main [website](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/tree/main/hotelontouch)

Currently, there is react icon favicon present in the title bar. We want to change it to the logo of the project. The logo is present [here](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/tree/main/hotelontouch/src/assets). Also change the name of logo_shreyanshi16.png to logo.png.

**Comment by khareyash05** [comment]
Hey ! Can i work on this issue?

**Comment by dhruvinfo28** [comment]
Hey, shall I work on this issue.

**Comment by JanviMahajan14** [comment]
Since it is First Come First Serve @khareyash05 you can go with it!
