### ISSUE TITLE
Enhancement in the main website 

### ISSUE THREAD

**Issue by ayan-biswas0412** [ayan-biswas0412/gssoc2021-HotelOnTouch#90]
**Is your feature request related to a problem? Please describe.**

Our Website is in the initial stage and all the development is done under the folder ```hotelontouch``` please go through that and we need more innovative ideas to make the website awesome , so more ideas are welcome here , please first discuss your idea in the comment and then if approved my a mentor then open an issue first and then start work on that . Please follow the mentioned steps otherwise your contribution will not be valid

cc @JanviMahajan14

**Comment by GuptaTanisha** [comment]
@ayan-biswas0412 Please assign this to me

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 Please assign this to me

first make sure you read the issue

**Comment by singhayushh** [comment]
Hello @ayan-biswas0412 ,
The very first feature that should be implemented is a user account creation - either as an admin or employee or customer.

**Customer Specific Features**
- Booking a hotel room
- Requesting either of laundry service, room service management, bar, restaurant order management
- Rating and reviewing

**Admin Specific Features**
- Customer management: operations to CRUD customers
- Employee management: operations to CRUD employees, reward badges for good reviews / performance
- Service management: operations to CRUD services, assign any service request to any of the employees, mark services as live / unattended / complete so that the employees can stay updated
- Room management: this will help keep a log of which rooms are booked, which rooms are available for booking etc

**Employees Specific Features**
- Attend to new service requests
- Log their work hours
- Apply for leave

**Comment by RiaKokate** [comment]
Hello @ayan-biswas0412 ,
I hope you are fine and doing well. 
I would like to work on this project . Would you please assign it to me?

**Comment by cryptofox17** [comment]
@ayan-biswas0412 I would like to work on this issue. 
I noticed that on desktop site the contribution section is taking most of the space because there are only 2 cards in each row. I want to improve on this arrangement. 
Also, the footer is not responsible so I want to fix It. 
Please assign this issue to me

**Comment by ayan-biswas0412** [comment]
> Hello @ayan-biswas0412 ,
> The very first feature that should be implemented is a user account creation - either as an admin or employee or customer.
> 
> **Customer Specific Features**
> 
> * Booking a hotel room
> * Requesting either of laundry service, room service management, bar, restaurant order management
> * Rating and reviewing
> 
> **Admin Specific Features**
> 
> * Customer management: operations to CRUD customers
> * Employee management: operations to CRUD employees, reward badges for good reviews / performance
> * Service management: operations to CRUD services, assign any service request to any of the employees, mark services as live / unattended / complete so that the employees can stay updated
> * Room management: this will help keep a log of which rooms are booked, which rooms are available for booking etc
> 
> **Employees Specific Features**
> 
> * Attend to new service requests
> * Log their work hours
> * Apply for leave

seems good you can make issue/s(maybe multiple issue on this and can start work) i will label with proper level according to the issues

**Comment by ayan-biswas0412** [comment]
> Hello @ayan-biswas0412 ,
> I hope you are fine and doing well.
> I would like to work on this project . Would you please assign it to me?

please read the issue once again

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 I would like to work on this issue.
> I noticed that on desktop site the contribution section is taking most of the space because there are only 2 cards in each row. I want to improve on this arrangement.
> Also, the footer is not responsible so I want to fix It.
> Please assign this issue to me

sure you can make one issue and start working

**Comment by ankitaugale23** [comment]
Hello, @ayan-biswas0412 I have 3 enhancements in my mind.
1. MAking the navbar look more lively.
2. Make some change to footer and adding some styling such as text over there will take less space (will add on hover kinda effects) so initially, it will take less space.
3. And the card at the top of the page we can add some effects to that too so it would look more attractive.
4. Will add a logo to the navbar (if you have any logo in your mind)
5. Will add styling to your card at the top so it will just show the photo and name at the start and after hovering over it, it will reveal other info, adding some more styles to it too.
Can I work on this?

**Comment by ayan-biswas0412** [comment]
> Hello, @ayan-biswas0412 I have 3 enhancements in my mind.
> 
> 1. MAking the navbar look more lively.
> 2. Make some change to footer and adding some styling such as text over there will take less space (will add on hover kinda effects) so initially, it will take less space.
> 3. And the card at the top of the page we can add some effects to that too so it would look more attractive.
> 4. Will add a logo to the navbar (if you have any logo in your mind)
> 5. Will add styling to your card at the top so it will just show the photo and name at the start and after hovering over it, it will reveal other info, adding some more styles to it too.
>    Can I work on this?

sure but make sure you open issues based on this (you may open multiple issues and after opening tag me such that I can assign proper levels on the issues)

**Comment by singhayushh** [comment]
@ayan-biswas0412

> seems good you can make issue/s(maybe multiple issue on this and can start work) i will label with proper level according to the issues

I have created issues for each of the major functionalities as milestones but I forgot to tag you in them. So, here's a gentle notice.

**Comment by ayan-biswas0412** [comment]
@singhayushh goo work , just edit all of your issues and then get back , I will assign you one by one

**Comment by singhayushh** [comment]
> @singhayushh goo work , just edit all of your issues and then get back , I will assign you one by one, already I have tagged them you can start working after proper edit of the issue bodies -> but again work on a single issue at a time

Yes definitely. I'll move on to next issues only when the previous PR gets reviewed and merged with all necessary amendments as required. 
I have edited all issue bodies and hopefully I can start working on them now...

**Comment by ankitaugale23** [comment]
> > Hello, @ayan-biswas0412 I have 3 enhancements in my mind.
> > 
> > 1. MAking the navbar look more lively.
> > 2. Make some change to footer and adding some styling such as text over there will take less space (will add on hover kinda effects) so initially, it will take less space.
> > 3. And the card at the top of the page we can add some effects to that too so it would look more attractive.
> > 4. Will add a logo to the navbar (if you have any logo in your mind)
> > 5. Will add styling to your card at the top so it will just show the photo and name at the start and after hovering over it, it will reveal other info, adding some more styles to it too.
> >    Can I work on this?
> 
> sure but make sure you open issues based on this (you may open multiple issues and after opening tag me such that I can assign proper levels on the issues)

Sure Thank you!
