### ISSUE TITLE
Switchable Dark Mode for website

### ISSUE THREAD

**Issue by Prajwal-ctrl** [ayan-biswas0412/gssoc2021-HotelOnTouch#94]
Hi @ayan-biswas0412 @shreyanshi16 i'm a GSSOC 21 participant can i work on this issue ? please let me know

**Comment by ayan-biswas0412** [comment]
@Prajwal-ctrl sure go ahead

**Comment by Prajwal-ctrl** [comment]
![Screenshot (69)_LI](https://user-images.githubusercontent.com/63673431/110800796-95889080-82a2-11eb-9268-4e0bb2938e90.jpg)


i have a dependency issues with material-ui yarn in hotelontouch directory package.json
i tried yarn with the other two directories , they work properly  , @ayan-biswas0412  can you please help with this one ?

**Comment by Prajwal-ctrl** [comment]
i am not able to start this with localhost

**Comment by ayan-biswas0412** [comment]
> i am not able to start this with localhost

remove node_modules/ and yarn.lock then perform yarn and yarn start again see what happens

**Comment by Prajwal-ctrl** [comment]
![Screenshot (72)](https://user-images.githubusercontent.com/63673431/110833260-3f2b4a00-82c2-11eb-93ae-e37a16a1e937.png)



### same issue most of the dependencies version are old i guess , i stuck on it only from last 4-5 hrs  😕 @JanviMahajan14  @ayan-biswas0412 @vinit-churi

**Comment by ayan-biswas0412** [comment]
> ![Screenshot (72)](https://user-images.githubusercontent.com/63673431/110833260-3f2b4a00-82c2-11eb-93ae-e37a16a1e937.png)
> 
> ### same issue most of the dependencies version are old i guess , i stuck on it only from last 4-5 hrs 😕 @JanviMahajan14 @ayan-biswas0412 @vinit-churi

reinstall node and yarn on your local machine

**Comment by Prajwal-ctrl** [comment]
![Screenshot (74)](https://user-images.githubusercontent.com/63673431/110936099-5d428a00-8356-11eb-8623-1ea1ac163a32.png)
![Screenshot (75)](https://user-images.githubusercontent.com/63673431/110936106-616ea780-8356-11eb-95ac-adf1d1ed9bd4.png)

### Here are some screenshots...

**Comment by Prajwal-ctrl** [comment]
![Screenshot (74)](https://user-images.githubusercontent.com/63673431/110936391-d4781e00-8356-11eb-8a81-0b6b49bb7ca0.png)
![Screenshot (75)](https://user-images.githubusercontent.com/63673431/110936401-d7730e80-8356-11eb-81d4-21d0a9392e20.png)

### @ayan-biswas0412  here are some screenshots . When we click on the Navbar button switch theme it switch to dark mode (vice-versa)

**Comment by ayan-biswas0412** [comment]
> ![Screenshot (74)](https://user-images.githubusercontent.com/63673431/110936391-d4781e00-8356-11eb-8a81-0b6b49bb7ca0.png)
> ![Screenshot (75)](https://user-images.githubusercontent.com/63673431/110936401-d7730e80-8356-11eb-81d4-21d0a9392e20.png)
> 
> ### @ayan-biswas0412 here are some screenshots . When we click on the Navbar button switch theme it switch to dark mode (vice-versa)

kindly make a PR such that i can review

**Comment by Prajwal-ctrl** [comment]
okay

**Comment by mohammedjameel24** [comment]
Assign me this issue am sure ill be able to add this feature

**Comment by ayan-biswas0412** [comment]
> Assign me this issue am sure ill be able to add this feature

sure

**Comment by farseenmanekhan1232** [comment]
What is the updates on this issue?
Is the issue resolved ?
If No , Can you please assign me this issue , I can try to help with this issue..

**Comment by ayan-biswas0412** [comment]
> What are the updates on this issue?
> Is the issue resolved ?
> If No , Can you please assign me this issue , I can contribute to this issue..

you can work

**Comment by mohammedjameel24** [comment]
Merged #128
