### ISSUE TITLE
Add favicon to the website

### ISSUE THREAD

**Issue by lavanya243** [ayan-biswas0412/gssoc2021-HotelOnTouch#95]
Add favicon feature to the website
[favicon (6).zip](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/files/6123503/favicon.6.zip)

Hey @ayan-biswas0412, @shreyanshi16 , @Anjali041, I am a GSSOC, 2021 participant and I want to add favicon feature in the website. Can I work on this issue?

**Comment by ayan-biswas0412** [comment]
@lavanya243 can you specify where you want to add this ?

**Comment by lavanya243** [comment]
Hi,
@ayan-biswas0412, I want to add the favicon feature in the files mentioned below:

1. gssoc2021-HotelOnTouch/hotel-admin-frontend/public/index.html
2. gssoc2021-HotelOnTouch/hotel-restraunt-frontend/public/index.html
3. gssoc2021-HotelOnTouch/hotelontouch/public/index.html

**Comment by ayan-biswas0412** [comment]
> Hi,
> @ayan-biswas0412, I want to add the favicon feature in the files mentioned below:
> 
> 1. gssoc2021-HotelOnTouch/hotel-admin-frontend/public/index.html
> 2. gssoc2021-HotelOnTouch/hotel-restraunt-frontend/public/index.html
> 3. gssoc2021-HotelOnTouch/hotelontouch/public/index.html

sure

**Comment by lavanya243** [comment]
@ayan-biswas0412 , Can i proceed with the issue?

And, I am unable to run the project. Can you please check?
![pic](https://user-images.githubusercontent.com/69483128/110902295-a4675580-832b-11eb-8998-8da7af0fcfbc.png)

**Comment by sahuaman83** [comment]
Can I work on this issue? I am able to run the project

**Comment by ayan-biswas0412** [comment]
> Can I work on this issue? I am able to run the project

go ahead
