### ISSUE TITLE
[Backend] Setting up the User Schema

### ISSUE THREAD

**Issue by singhayushh** [ayan-biswas0412/gssoc2021-HotelOnTouch#98]
### Issue Reference
[View Issue Reference](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/issues/90#issuecomment-797267459)

### About this issue
Currently, there's just a dummy backend server setup for the project. To start with, the first focus must be setting up the user schema. As mentioned in the reference issue comment, there are to be three types of users - admin, employee and customer.
I will be working on the same - setting up models for all three type of users and sending a PR for your reviewing and amendments.

**Comment by ayan-biswas0412** [comment]
@singhayushh I see that you have referenced all of your PRs at all the issues , but please keep one PR -> one issue that will be easy for us to track changes

**Comment by singhayushh** [comment]
@ayan-biswas0412 
Yes surely, I'll be doing that!

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412
> Yes surely, I'll be doing that!

sure please edit all of the issues

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412
> Yes surely, I'll be doing that!
> 
> I haven't created any PRs yet. These are just the issue raising before I start to work on them.
> The references are from the comment on the previous issue where I listed all of the functionalities.

sorry my bad ... please edit the issue bodies

**Comment by udaymittal7** [comment]
I want to work on the user schema, routes and controller.

**Comment by ayan-biswas0412** [comment]
> I want to work on the user schema, routes and controller.

@singhayushh can you guide him and divide tasks between yourself

**Comment by singhayushh** [comment]
Hello, the last merged PR covered this issue. Can you please assign this to me before closing the issue for the records?
