### ISSUE TITLE
[Backend] Setting up the Service Schema

### ISSUE THREAD

**Issue by singhayushh** [ayan-biswas0412/gssoc2021-HotelOnTouch#99]
### Issue Reference
[View Issue Reference](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/issues/90#issuecomment-797267459)

### About this issue
Following the user schema, the next focus is to set up the service schema. Services include laundry service, room service management, bar, restaurant order management etc as to be added by the admin.

**Comment by abhinav5481** [comment]
I would like to work on it as part of GSSOC'21. Could you please assign this issue to me?

**Comment by singhayushh** [comment]
@abhinav5481 
I created a series of 6 issues to be self assigned actually. 

There are a lot of other parts in the backend you can take up!

**Comment by ayan-biswas0412** [comment]
@singhayushh are you in my project discord channel then we can discuss further on backend and @abhinav5481 please wait for @singhayushh he is managing the backend issues for now
